let names = [
			"Aerie",
			"Argosy",
			"Arrow",
			"Bactrian",
			"Barb Barb (Proton)",
			"Barb",
			"Bastion",
			"Behemoth",
			"Berserker",
			"Blackbird",
			"Bounder",
			"Boxwing",
			"Bulk Freighter",
			"Carrier",
			"Class C Freighter",
			"Clipper",
			"Combat Drone",
			"Corvette",
			"Cruiser",
			"Dagger",
			"Dreadnought",
			"Falcon",
			"Finch",
			"Firebird",
			"Flivver",
			"Freighter",
			"Frigate",
			"Fury",
			"Gunboat",
			"Hauler II",
			"Hauler III",
			"Hauler",
			"Hawk",
			"Headhunter",
			"Heavy Shuttle",
			"Lance",
			"Leviathan",
			"Manta",
			"Modified Argosy",
			"Mule",
			"Nest",
			"Osprey",
			"Protector",
			"Quicksilver",
			"Rainmaker",
			"Raven",
			"Roost",
			"Scout",
			"Shuttle",
			"Skein",
			"Sparrow",
			"Splinter",
			"Star Barge",
			"Star Queen",
			"Surveillance Drone",
			"Vanguard",
			"Wasp",

			"Cooling Ducts",
			"Liquid Helium Cooler",
			"Liquid Nitrogen Cooler",
			"Water Coolant System",
			"LP036a Battery Pack",
			"LP072a Battery Pack",
			"LP144a Battery Pack",
			"LP288a Battery Pack",
			"LP576a Battery Pack",
			"Supercapacitor",
			"Armageddon Core",
			"Breeder Reactor",
			"Dwarf Core",
			"Fission Reactor",
			"Fusion Reactor",
			"KP-6 Photovoltaic Array",
			"KP-6 Photovoltaic Panel",
			"nGVF-AA Fuel Cell",
			"nGVF-BB Fuel Cell",
			"nGVF-CC Fuel Cell",
			"nGVF-DD Fuel Cell",
			"nGVF-EE Fuel Cell",
			"NT-200 Nucleovoltaic",
			"RT-I Radiothermal",
			"S3 Thermionic",
			"Stack Core",
			"Afterburner",
			"AR120 Reverse Thruster",
			"Ionic Afterburner",
			"A125 Atomic Steering",
			"A255 Atomic Steering",
			"A375 Atomic Steering",
			"A525 Atomic Steering",
			"A865 Atomic Steering",
			"Chipmunk Plasma Steering",
			"Greyhound Plasma Steering",
			"Impala Plasma Steering",
			"Orca Plasma Steering",
			"Tyrant Plasma Steering",
			"X1050 Ion Engines",
			"X1200 Ion Steering",
			"X2200 Ion Steering",
			"X3200 Ion Steering",
			"X4200 Ion Steering",
			"X5200 Ion Steering",
			"A120 Atomic Thruster",
			"A250 Atomic Thruster",
			"A370 Atomic Thruster",
			"A520 Atomic Thruster",
			"A860 Atomic Thruster",
			"Chipmunk Plasma Thruster",
			"Greyhound Plasma Thruster",
			"Impala Plasma Thruster",
			"Orca Plasma Thruster",
			"Tyrant Plasma Thruster",
			"X1050 Ion Engines",
			"X1700 Ion Thruster",
			"X2700 Ion Thruster",
			"X3700 Ion Thruster",
			"X4700 Ion Thruster",
			"X5700 Ion Thruster",
			"Fragmentation Grenades",
			"Laser Rifle",
			"Nerve Gas",
			"Security Station",
			"D14-RN Shield Generator",
			"D23-QP Shield Generator",
			"D41-HY Shield Generator",
			"D67-TM Shield Generator",
			"D94-YV Shield Generator",
			"S-270 Regenerator",
			"S-970 Regenerator",
			"Local Map",
			"Pilots License",
			"Bunk Room",
			"Cargo Expansion",
			"Cargo Scanner",
			"Catalytic Ramscoop",
			"Cloaking Device",
			"Fuel Pod",
			"Hyperdrive",
			"Interference Plating",
			"Jump Drive",
			"Large Radar Jammer",
			"Outfit Scanner",
			"Outfits Expansion",
			"Ramscoop",
			"Scram Drive",
			"Small Bunk Room",
			"Small Radar Jammer",
			"Surveillance Pod",
			"Bullet Boxes",
			"Gatling Gun Ammo",
			"Heavy Rocket Rack",
			"Heavy Rocket",
			"Javelin Storage Crate",
			"Javelin",
			"Meteor Missile Box",
			"Meteor Missile",
			"Sidewinder Missile Rack",
			"Sidewinder Missile",
			"Torpedo Storage Rack",
			"Torpedo",
			"Typhoon Storage Tube",
			"Typhoon Torpedo",
			"Beam Laser",
			"Electron Beam",
			"Energy Blaster",
			"Heavy Laser",
			"Modified Blaster",
			"Particle Cannon",
			"Plasma Cannon",
			"Proton Gun",
			"Flamethrower Projectile",
			"gbullet",
			"Proton Fragment",
			"Flamethrower",
			"Gatling Gun",
			"Heavy Rocket Launcher",
			"Javelin Pod",
			"Meteor Missile Launcher",
			"Nuclear Missile",
			"Sidewinder Missile Launcher",
			"Torpedo Launcher",
			"Typhoon Launcher",
			"Anti-Missile Turret",
			"Blaster Turret",
			"Electron Turret",
			"Heavy Anti-Missile Turret",
			"Heavy Laser Turret",
			"Laser Turret",
			"Modified Blaster Turret",
			"Plasma Turret",
			"Quad Blaster Turret"
];

let search = [
			"aerie",
			"argosy",
			"arrow",
			"bactrian",
			"barb barb (proton)",
			"barb",
			"bastion",
			"behemoth",
			"berserker",
			"blackbird",
			"bounder",
			"boxwing",
			"bulk freighter",
			"carrier",
			"class c freighter",
			"clipper",
			"combat drone",
			"corvette",
			"cruiser",
			"dagger",
			"dreadnought",
			"falcon",
			"finch",
			"firebird",
			"flivver",
			"freighter",
			"frigate",
			"fury",
			"gunboat",
			"hauler ii",
			"hauler iii",
			"hauler",
			"hawk",
			"headhunter",
			"heavy shuttle",
			"lance",
			"leviathan",
			"manta",
			"modified argosy",
			"mule",
			"nest",
			"osprey",
			"protector",
			"quicksilver",
			"rainmaker",
			"raven",
			"roost",
			"scout",
			"shuttle",
			"skein",
			"sparrow",
			"splinter",
			"star barge",
			"star queen",
			"surveillance drone",
			"vanguard",
			"wasp",

			"cooling ducts",
			"liquid helium cooler",
			"liquid nitrogen cooler",
			"water coolant system",
			"lp036a battery pack",
			"lp072a battery pack",
			"lp144a battery pack",
			"lp288a battery pack",
			"lp576a battery pack",
			"supercapacitor",
			"armageddon core",
			"breeder reactor",
			"dwarf core",
			"fission reactor",
			"fusion reactor",
			"kp-6 photovoltaic array",
			"kp-6 photovoltaic panel",
			"ngvf-aa fuel cell",
			"ngvf-bb fuel cell",
			"ngvf-cc fuel cell",
			"ngvf-dd fuel cell",
			"ngvf-ee fuel cell",
			"nt-200 nucleovoltaic",
			"rt-i radiothermal",
			"s3 thermionic",
			"stack core",
			"afterburner",
			"ar120 reverse thruster",
			"ionic afterburner",
			"a125 atomic steering",
			"a255 atomic steering",
			"a375 atomic steering",
			"a525 atomic steering",
			"a865 atomic steering",
			"chipmunk plasma steering",
			"greyhound plasma steering",
			"impala plasma steering",
			"orca plasma steering",
			"tyrant plasma steering",
			"x1050 ion engines",
			"x1200 ion steering",
			"x2200 ion steering",
			"x3200 ion steering",
			"x4200 ion steering",
			"x5200 ion steering",
			"a120 atomic thruster",
			"a250 atomic thruster",
			"a370 atomic thruster",
			"a520 atomic thruster",
			"a860 atomic thruster",
			"chipmunk plasma thruster",
			"greyhound plasma thruster",
			"impala plasma thruster",
			"orca plasma thruster",
			"tyrant plasma thruster",
			"x1050 ion engines",
			"x1700 ion thruster",
			"x2700 ion thruster",
			"x3700 ion thruster",
			"x4700 ion thruster",
			"x5700 ion thruster",
			"fragmentation grenades",
			"laser rifle",
			"nerve gas",
			"security station",
			"d14-rn shield generator",
			"d23-qp shield generator",
			"d41-hy shield generator",
			"d67-tm shield generator",
			"d94-yv shield generator",
			"s-270 regenerator",
			"s-970 regenerator",
			"local map",
			"pilots license",
			"bunk room",
			"cargo expansion",
			"cargo scanner",
			"catalytic ramscoop",
			"cloaking device",
			"fuel pod",
			"hyperdrive",
			"interference plating",
			"jump drive",
			"large radar jammer",
			"outfit scanner",
			"outfits expansion",
			"ramscoop",
			"scram drive",
			"small bunk room",
			"small radar jammer",
			"surveillance pod",
			"bullet boxes",
			"gatling gun ammo",
			"heavy rocket rack",
			"heavy rocket",
			"javelin storage crate",
			"javelin",
			"meteor missile box",
			"meteor missile",
			"sidewinder missile rack",
			"sidewinder missile",
			"torpedo storage rack",
			"torpedo",
			"typhoon storage tube",
			"typhoon torpedo",
			"beam laser",
			"electron beam",
			"energy blaster",
			"heavy laser",
			"modified blaster",
			"particle cannon",
			"plasma cannon",
			"proton gun",
			"flamethrower projectile",
			"gbullet",
			"proton fragment",
			"flamethrower",
			"gatling gun",
			"heavy rocket launcher",
			"javelin pod",
			"meteor missile launcher",
			"nuclear missile",
			"sidewinder missile launcher",
			"torpedo launcher",
			"typhoon launcher",
			"anti-missile turret",
			"blaster turret",
			"electron turret",
			"heavy anti-missile turret",
			"heavy laser turret",
			"laser turret",
			"modified blaster turret",
			"plasma turret",
			"quad blaster turret"
];

let paths = [
			"ships/Aerie",
			"ships/Argosy",
			"ships/Arrow",
			"ships/Bactrian",
			"ships/Barb Barb (Proton)",
			"ships/Barb",
			"ships/Bastion",
			"ships/Behemoth",
			"ships/Berserker",
			"ships/Blackbird",
			"ships/Bounder",
			"ships/Boxwing",
			"ships/Bulk Freighter",
			"ships/Carrier",
			"ships/Class C Freighter",
			"ships/Clipper",
			"ships/Combat Drone",
			"ships/Corvette",
			"ships/Cruiser",
			"ships/Dagger",
			"ships/Dreadnought",
			"ships/Falcon",
			"ships/Finch",
			"ships/Firebird",
			"ships/Flivver",
			"ships/Freighter",
			"ships/Frigate",
			"ships/Fury",
			"ships/Gunboat",
			"ships/Hauler II",
			"ships/Hauler III",
			"ships/Hauler",
			"ships/Hawk",
			"ships/Headhunter",
			"ships/Heavy Shuttle",
			"ships/Lance",
			"ships/Leviathan",
			"ships/Manta",
			"ships/Modified Argosy",
			"ships/Mule",
			"ships/Nest",
			"ships/Osprey",
			"ships/Protector",
			"ships/Quicksilver",
			"ships/Rainmaker",
			"ships/Raven",
			"ships/Roost",
			"ships/Scout",
			"ships/Shuttle",
			"ships/Skein",
			"ships/Sparrow",
			"ships/Splinter",
			"ships/Star Barge",
			"ships/Star Queen",
			"ships/Surveillance Drone",
			"ships/Vanguard",
			"ships/Wasp",

			"outfits/cooling/Cooling Ducts",
			"outfits/cooling/Liquid Helium Cooler",
			"outfits/cooling/Liquid Nitrogen Cooler",
			"outfits/cooling/Water Coolant System",
			"outfits/energy/batteries/LP036a Battery Pack",
			"outfits/energy/batteries/LP072a Battery Pack",
			"outfits/energy/batteries/LP144a Battery Pack",
			"outfits/energy/batteries/LP288a Battery Pack",
			"outfits/energy/batteries/LP576a Battery Pack",
			"outfits/energy/batteries/Supercapacitor",
			"outfits/energy/generators/Armageddon Core",
			"outfits/energy/generators/Breeder Reactor",
			"outfits/energy/generators/Dwarf Core",
			"outfits/energy/generators/Fission Reactor",
			"outfits/energy/generators/Fusion Reactor",
			"outfits/energy/generators/KP-6 Photovoltaic Array",
			"outfits/energy/generators/KP-6 Photovoltaic Panel",
			"outfits/energy/generators/nGVF-AA Fuel Cell",
			"outfits/energy/generators/nGVF-BB Fuel Cell",
			"outfits/energy/generators/nGVF-CC Fuel Cell",
			"outfits/energy/generators/nGVF-DD Fuel Cell",
			"outfits/energy/generators/nGVF-EE Fuel Cell",
			"outfits/energy/generators/NT-200 Nucleovoltaic",
			"outfits/energy/generators/RT-I Radiothermal",
			"outfits/energy/generators/S3 Thermionic",
			"outfits/energy/generators/Stack Core",
			"outfits/engines/special/Afterburner",
			"outfits/engines/special/AR120 Reverse Thruster",
			"outfits/engines/special/Ionic Afterburner",
			"outfits/engines/steering/A125 Atomic Steering",
			"outfits/engines/steering/A255 Atomic Steering",
			"outfits/engines/steering/A375 Atomic Steering",
			"outfits/engines/steering/A525 Atomic Steering",
			"outfits/engines/steering/A865 Atomic Steering",
			"outfits/engines/steering/Chipmunk Plasma Steering",
			"outfits/engines/steering/Greyhound Plasma Steering",
			"outfits/engines/steering/Impala Plasma Steering",
			"outfits/engines/steering/Orca Plasma Steering",
			"outfits/engines/steering/Tyrant Plasma Steering",
			"outfits/engines/steering/X1050 Ion Engines",
			"outfits/engines/steering/X1200 Ion Steering",
			"outfits/engines/steering/X2200 Ion Steering",
			"outfits/engines/steering/X3200 Ion Steering",
			"outfits/engines/steering/X4200 Ion Steering",
			"outfits/engines/steering/X5200 Ion Steering",
			"outfits/engines/thrusters/A120 Atomic Thruster",
			"outfits/engines/thrusters/A250 Atomic Thruster",
			"outfits/engines/thrusters/A370 Atomic Thruster",
			"outfits/engines/thrusters/A520 Atomic Thruster",
			"outfits/engines/thrusters/A860 Atomic Thruster",
			"outfits/engines/thrusters/Chipmunk Plasma Thruster",
			"outfits/engines/thrusters/Greyhound Plasma Thruster",
			"outfits/engines/thrusters/Impala Plasma Thruster",
			"outfits/engines/thrusters/Orca Plasma Thruster",
			"outfits/engines/thrusters/Tyrant Plasma Thruster",
			"outfits/engines/thrusters/X1050 Ion Engines",
			"outfits/engines/thrusters/X1700 Ion Thruster",
			"outfits/engines/thrusters/X2700 Ion Thruster",
			"outfits/engines/thrusters/X3700 Ion Thruster",
			"outfits/engines/thrusters/X4700 Ion Thruster",
			"outfits/engines/thrusters/X5700 Ion Thruster",
			"outfits/hand to hand/Fragmentation Grenades",
			"outfits/hand to hand/Laser Rifle",
			"outfits/hand to hand/Nerve Gas",
			"outfits/hand to hand/Security Station",
			"outfits/shield/D14-RN Shield Generator",
			"outfits/shield/D23-QP Shield Generator",
			"outfits/shield/D41-HY Shield Generator",
			"outfits/shield/D67-TM Shield Generator",
			"outfits/shield/D94-YV Shield Generator",
			"outfits/shield/S-270 Regenerator",
			"outfits/shield/S-970 Regenerator",
			"outfits/special/Local Map",
			"outfits/special/Pilots License",
			"outfits/systems/Bunk Room",
			"outfits/systems/Cargo Expansion",
			"outfits/systems/Cargo Scanner",
			"outfits/systems/Catalytic Ramscoop",
			"outfits/systems/Cloaking Device",
			"outfits/systems/Fuel Pod",
			"outfits/systems/Hyperdrive",
			"outfits/systems/Interference Plating",
			"outfits/systems/Jump Drive",
			"outfits/systems/Large Radar Jammer",
			"outfits/systems/Outfit Scanner",
			"outfits/systems/Outfits Expansion",
			"outfits/systems/Ramscoop",
			"outfits/systems/Scram Drive",
			"outfits/systems/Small Bunk Room",
			"outfits/systems/Small Radar Jammer",
			"outfits/systems/Surveillance Pod",
			"outfits/weapons/ammunition/Bullet Boxes",
			"outfits/weapons/ammunition/Gatling Gun Ammo",
			"outfits/weapons/ammunition/Heavy Rocket Rack",
			"outfits/weapons/ammunition/Heavy Rocket",
			"outfits/weapons/ammunition/Javelin Storage Crate",
			"outfits/weapons/ammunition/Javelin",
			"outfits/weapons/ammunition/Meteor Missile Box",
			"outfits/weapons/ammunition/Meteor Missile",
			"outfits/weapons/ammunition/Sidewinder Missile Rack",
			"outfits/weapons/ammunition/Sidewinder Missile",
			"outfits/weapons/ammunition/Torpedo Storage Rack",
			"outfits/weapons/ammunition/Torpedo",
			"outfits/weapons/ammunition/Typhoon Storage Tube",
			"outfits/weapons/ammunition/Typhoon Torpedo",
			"outfits/weapons/guns/Beam Laser",
			"outfits/weapons/guns/Electron Beam",
			"outfits/weapons/guns/Energy Blaster",
			"outfits/weapons/guns/Heavy Laser",
			"outfits/weapons/guns/Modified Blaster",
			"outfits/weapons/guns/Particle Cannon",
			"outfits/weapons/guns/Plasma Cannon",
			"outfits/weapons/guns/Proton Gun",
			"outfits/weapons/projectiles/Flamethrower Projectile",
			"outfits/weapons/projectiles/gbullet",
			"outfits/weapons/projectiles/Proton Fragment",
			"outfits/weapons/secondary weapons/Flamethrower",
			"outfits/weapons/secondary weapons/Gatling Gun",
			"outfits/weapons/secondary weapons/Heavy Rocket Launcher",
			"outfits/weapons/secondary weapons/Javelin Pod",
			"outfits/weapons/secondary weapons/Meteor Missile Launcher",
			"outfits/weapons/secondary weapons/Nuclear Missile",
			"outfits/weapons/secondary weapons/Sidewinder Missile Launcher",
			"outfits/weapons/secondary weapons/Torpedo Launcher",
			"outfits/weapons/secondary weapons/Typhoon Launcher",
			"outfits/weapons/turrets/Anti-Missile Turret",
			"outfits/weapons/turrets/Blaster Turret",
			"outfits/weapons/turrets/Electron Turret",
			"outfits/weapons/turrets/Heavy Anti-Missile Turret",
			"outfits/weapons/turrets/Heavy Laser Turret",
			"outfits/weapons/turrets/Laser Turret",
			"outfits/weapons/turrets/Modified Blaster Turret",
			"outfits/weapons/turrets/Plasma Turret",
			"outfits/weapons/turrets/Quad Blaster Turret"
];