var stats = {
	"cost_min": 50000,
	"cost": "bad",
	"cost_max": 1000000000,

	"shields_min": 200,
	"shields": "good",
	"shields_max": 4000000,

	"hull_min": 200,
	"hull": "good",
	"hull_max": 1000000,

	"required_crew_min": 1,
	"required_crew": "bad",
	"required_crew_max": 794,

	"bunks_min": 1,
	"bunks": "good",
	"bunks_max": 1492,

	"mass_min": 15,
	"mass": "bad",
	"mass_max": 1735,

	"drag_min": 0.53,
	"drag": "bad",
	"drag_max": 27,

	"heat_dissipation_min": 0.27,
	"heat_dissipation": "good",
	"heat_dissipation_max": 40,

	"fuel_capacity_min": 200,
	"fuel_capacity": "good",
	"fuel_capacity_max": 1200,

	"cargo_space_min": 0,
	"cargo_space": "good",
	"cargo_space_max": 1140,

	"outfit_space_min": 45,
	"outfit_space": "good",
	"outfit_space_max": 1054,

	"weapon_capacity_min": 0,
	"weapon_capacity": "good",
	"weapon_capacity_max": 600,

	"engine_capacity_min": 22,
	"engine_capacity": "good",
	"engine_capacity_max": 220,

	"shield_generation_min": 0.6,
	"shield_generation": "good",
	"shield_generation_max": 100,

	"shield_energy_min": 0.4,
	"shield_energy": "good",
	"shield_energy_max": 100,

	"hull_repair_rate_min": 0.8,
	"hull_repair_rate": "good",
	"hull_repair_rate_max": 100,

	"hull_energy_min": 0.6,
	"hull_energy": "good",
	"hull_energy_max": 100,

	"energy_capacity_min": 1000,
	"energy_capacity": "good",
	"energy_capacity_max": 10000,

	"energy_generation_min": 10,
	"energy_generation": "good",
	"energy_generation_max": 500,

	"heat_generation_min": 10,
	"heat_generation": "bad",
	"heat_generation_max": 48,

	"ramscoop_min": 2,
	"ramscoop": "good",
	"ramscoop_max": 100,

	"atmosphere_scan_min": 100,
	"atmosphere_scan": "good",
	"atmosphere_scan_max": 100,

	"self_destruct_min": 0.15,
	"self_destruct": "bad",
	"self_destruct_max": 0.8,

	"cloaking_fuel_min": -0.2,
	"cloaking_fuel": "bad",
	"cloaking_fuel_max": 0.1,

	"cloak_min": 0.02,
	"cloak": "good",
	"cloak_max": 0.02,

	"cloaking_energy_min": 5,
	"cloaking_energy": "bad",
	"cloaking_energy_max": 5,

	"group": [
		["cost", "mass"],
		["shields", "hull", "bunks", "heat_dissipation", "fuel_capacity", "cargo_space", "outfit_space", "weapon_capacity", "engine_capacity", "shield_generation", "shield_energy", "hull_repair_rate", "hull_energy", "energy_capacity", "energy_generation", "ramscoop", "atmosphere_scan", "cloak"],
		["required_crew", "drag", "heat_generation", "self_destruct", "cloaking_fuel", "cloaking_energy"]
	]
}

var ships = {
	"Aerie": {
		"upper": "Aerie",
		"lower": "aerie",
		"race": "Human",
		"sprite": "ship/aerie",
		"attributes": {
			"category": "Medium Warship",
			"cost": 3500000,
			"shields": 5700,
			"hull": 1900,
			"required_crew": 10,
			"bunks": 28,
			"mass": 130,
			"drag": 4.1,
			"heat_dissipation": 0.7,
			"fuel_capacity": 500,
			"cargo_space": 50,
			"outfit_space": 390,
			"weapon_capacity": 150,
			"engine_capacity": 95
		},
		"description": "The Lionheart Aerie is a light carrier, designed to be just big enough for two fighter bays plus a decent armament of its own. Variations on this same ship design have been in use in the Deep for almost half a millennium, but this model comes with the very latest in generator and weapon technology."
	},
	"Albatross": {
		"upper": "Albatross",
		"lower": "albatross",
		"race": "Remnant",
		"sprite": "ship/albatross",
		"attributes": {
			"category": "Heavy Warship",
			"licenses": {
				"Remnant": 1
			},
			"cost": 20000000,
			"shields": 34200,
			"hull": 12600,
			"required_crew": 44,
			"bunks": 75,
			"cargo_space": 124,
			"mass": 610,
			"drag": 8.6,
			"heat_dissipation": 0.6,
			"fuel_capacity": 600,
			"engine_capacity": 142,
			"outfit_space": 658,
			"weapon_capacity": 236,
			"shield_generation": 5.2,
			"shield_energy": 4.6,
			"hull_repair_rate": 1.5,
			"hull_energy": 1.2
		},
		"description": "Once they left human space, it became apparent to the Remnant that they would need to build their own shipyards in order to defend themselves if they were discovered by the Alphas or any other unfriendly faction. Using new composite materials that they discovered, they built ships very different from anything seen in human space."
	},
	"Aphid": {
		"upper": "Aphid",
		"lower": "aphid",
		"race": "Hai",
		"sprite": "ship/hai aphid",
		"attributes": {
			"category": "Light Freighter",
			"cost": 570000,
			"shields": 1700,
			"hull": 1400,
			"required_crew": 1,
			"bunks": 5,
			"mass": 100,
			"drag": 1.9,
			"heat_dissipation": 0.9,
			"fuel_capacity": 400,
			"cargo_space": 51,
			"outfit_space": 185,
			"weapon_capacity": 37,
			"engine_capacity": 48
		},
		"description": "The Aphid is a light freighter designed by the Hai. It has only minimal armament."
	},
	"Arach Courier": {
		"upper": "Arach Courier",
		"lower": "arach courier",
		"race": "Coalition",
		"sprite": "ship/arach courier",
		"attributes": {
			"category": "Light Freighter",
			"licenses": {
				"Coalition": 1
			},
			"cost": 723000,
			"shields": 1200,
			"hull": 2000,
			"required_crew": 1,
			"bunks": 1,
			"mass": 100,
			"drag": 2.9,
			"heat_dissipation": 0.65,
			"fuel_capacity": 300,
			"cargo_space": 78,
			"outfit_space": 148,
			"weapon_capacity": 39,
			"engine_capacity": 40
		},
		"description": "These hardy little cargo ships are the perfect size for young Arachi just setting out into the sky with dreams of one day building their own merchant fleets. Of course, an Arach lucky enough to be born into one of the great Houses can probably find a patron to buy them a much larger ship instead."
	},
	"Arach Freighter": {
		"upper": "Arach Freighter",
		"lower": "arach freighter",
		"race": "Coalition",
		"sprite": "ship/arach freighter",
		"attributes": {
			"category": "Light Freighter",
			"licenses": {
				"Coalition": 1
			},
			"cost": 4580000,
			"shields": 3400,
			"hull": 8500,
			"required_crew": 3,
			"bunks": 10,
			"mass": 380,
			"drag": 10.6,
			"heat_dissipation": 0.55,
			"fuel_capacity": 500,
			"cargo_space": 310,
			"outfit_space": 349,
			"weapon_capacity": 132,
			"engine_capacity": 92
		},
		"description": "Arach cargo ship hulls are legendary for their durability. It is not uncommon for a large Arach family to convert a freighter that is no longer space-worthy into a planet-side dwelling, and even in the harshest of conditions these converted houses can last for hundreds of years with little or no exterior maintenance."
	},
	"Arach Hulk": {
		"upper": "Arach Hulk",
		"lower": "arach hulk",
		"race": "Coalition",
		"sprite": "ship/arach hulk",
		"attributes": {
			"category": "Heavy Freighter",
			"licenses": {
				"Coalition": 1
			},
			"cost": 9978000,
			"shields": 5700,
			"hull": 13800,
			"required_crew": 8,
			"bunks": 14,
			"mass": 670,
			"drag": 18.9,
			"heat_dissipation": 0.5,
			"fuel_capacity": 500,
			"cargo_space": 541,
			"outfit_space": 520,
			"weapon_capacity": 208,
			"engine_capacity": 148
		},
		"description": "The Arachi believe that efficient functionality is the highest form of beauty, and none of their ships demonstrate that principle more clearly than the ugly yet utilitarian Hulk, designed with detachable side pods that can be swapped out on a planet in a matter of minutes if the captain is in a hurry to reach the next destination."
	},
	"Arach Spindle": {
		"upper": "Arach Spindle",
		"lower": "arach spindle",
		"race": "Coalition",
		"sprite": "ship/arach spindle",
		"attributes": {
			"category": "Heavy Freighter",
			"licenses": {
				"Coalition": 1
			},
			"cost": 6652000,
			"shields": 5000,
			"hull": 9700,
			"required_crew": 4,
			"bunks": 14,
			"mass": 340,
			"drag": 10.8,
			"heat_dissipation": 0.55,
			"fuel_capacity": 500,
			"cargo_space": 280,
			"outfit_space": 434,
			"weapon_capacity": 138,
			"engine_capacity": 148
		},
		"description": "The Arach Hulk is an ungainly, lumbering behemoth of a ship, but with its side pods removed it becomes the much more maneuverable Spindle. Because of its much lower cargo space, usually the only reason a fleet would include a Spindle is if they are planning on picking up new cargo pods at their destination."
	},
	"Arach Transport": {
		"upper": "Arach Transport",
		"lower": "arach transport",
		"race": "Coalition",
		"sprite": "ship/arach transport",
		"attributes": {
			"category": "Light Freighter",
			"licenses": {
				"Coalition": 1
			},
			"cost": 2772000,
			"shields": 2300,
			"hull": 4800,
			"required_crew": 2,
			"bunks": 5,
			"mass": 280,
			"drag": 7.2,
			"heat_dissipation": 0.6,
			"fuel_capacity": 400,
			"cargo_space": 190,
			"outfit_space": 281,
			"weapon_capacity": 96,
			"engine_capacity": 70
		},
		"description": "The Arach Transport is the oldest of their ship designs, dating back to the time when they first joined the Coalition in overthrowing the Quarg and capturing their ringworlds. Back then, Transports were occasionally used as warships, but now, thousands of years later, they are considered outdated compared to the latest Heliarch military ships."
	},
	"Archon": {
		"upper": "Archon",
		"lower": "archon",
		"race": "Drak",
		"noun": "entity",
		"sprite": "ship/archon-0",
		"never_disabled": 1,
		"attributes": {
			"category": "Heavy Warship",
			"cost": 1000000000,
			"shields": 4000000,
			"hull": 1000000,
			"required_crew": 1,
			"bunks": 1,
			"mass": 1000,
			"drag": 27,
			"heat_dissipation": 40,
			"fuel_capacity": 800,
			"cargo_space": 0,
			"outfit_space": 800,
			"weapon_capacity": 600,
			"engine_capacity": 200,
			"energy_capacity": 10000,
			"energy_generation": 500,
			"shield_generation": 100,
			"shield_energy": 100,
			"hull_repair_rate": 100,
			"hull_energy": 100,
			"heat_generation": 17,
			"ramscoop": 100
		},
		"description": "This ship doesn't have a description."
	},
	"Argosy": {
		"race": "Human",
		"plural": "Argosies",
		"sprite": "ship/argosy",
		"attributes": {
			"category": "Light Freighter",
			"cost": 1960000,
			"shields": 4200,
			"hull": 2600,
			"required_crew": 4,
			"bunks": 14,
			"mass": 330,
			"drag": 5.9,
			"heat_dissipation": 0.7,
			"fuel_capacity": 400,
			"cargo_space": 120,
			"outfit_space": 270,
			"weapon_capacity": 90,
			"engine_capacity": 80
		},
		"description": [
			"The Argosy from Southbound Shipyards is very popular with merchants not because of its capacity, which is actually slightly smaller than the Syndicate Freighter, but because it can hold its own in combat even against a small pirate fleet.",
			"The Argosy is also a very easy ship to upgrade with faster engines or more powerful weapons as needed, so many privately owned Argosies have very different capabilities than the stock model."
		]
	},
	"Arrow": {
		"upper": "Arrow",
		"lower": "arrow",
		"race": "Human",
		"sprite": "ship/arrow",
		"attributes": {
			"category": "Transport",
			"cost": 1200000,
			"shields": 2000,
			"hull": 400,
			"required_crew": 1,
			"bunks": 5,
			"mass": 130,
			"drag": 2.7,
			"heat_dissipation": 0.85,
			"fuel_capacity": 400,
			"cargo_space": 10,
			"outfit_space": 180,
			"weapon_capacity": 50,
			"engine_capacity": 60
		},
		"description": "The Arrow is a light transport, designed for bringing a small number of very rich passengers - Syndicate CEOs, for example - from one planet to another with speed and style. It makes up for its light armament by being able to outrun nearly every other ship in the sky."
	},
	"Autumn Leaf": {
		"upper": "Autumn Leaf",
		"lower": "autumn leaf",
		"race": "Wanderer",
		"sprite": "ship/autumn leaf",
		"attributes": {
			"category": "Light Warship",
			"licenses": {
				"Wanderer": 1
			},
			"cost": 12500000,
			"shields": 18700,
			"hull": 7400,
			"required_crew": 8,
			"bunks": 16,
			"mass": 130,
			"drag": 2.9,
			"heat_dissipation": 0.8,
			"fuel_capacity": 1000,
			"cargo_space": 45,
			"outfit_space": 361,
			"weapon_capacity": 103,
			"engine_capacity": 117
		},
		"description": "The Autumn Leaf is based on the Wanderer Summer Leaf light warship, but slightly larger and better equipped for combat. Unlike Wanderer peacetime ships, it is equipped with a turret mount in addition to the ports for fixed guns."
	},
	"Bactrian": {
		"upper": "Bactrian",
		"lower": "bactrian",
		"race": "Human",
		"sprite": "ship/bactrian",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 17600000,
			"shields": 17500,
			"hull": 8600,
			"required_crew": 70,
			"bunks": 245,
			"mass": 940,
			"drag": 16.1,
			"heat_dissipation": 0.4,
			"fuel_capacity": 700,
			"cargo_space": 530,
			"outfit_space": 740,
			"weapon_capacity": 300,
			"engine_capacity": 180
		},
		"description": "The Lionheart Bactrian is the last of the great city-ships, a design hearkening back to the early days of space colonization when a long-distance vessel needed to be a self-contained world, able to survive for weeks at a time without encountering an inhabited planet. It is not only a freighter, but a carrier, and a capable warship either at short range or at a distance. Naturally, this versatility also makes it extremely expensive, and the Bactrian is not normally for sale to ordinary citizens who have not been vetted by the local government of the Deep."
	},
	"Barb Barb (Proton)": {
		"upper": "Barb Barb (Proton)",
		"lower": "barb barb (proton)",
		"race": "Human",
		"sprite": "ship/barbp",
		"attributes": {
			"category": "Fighter",
			"cost": 50000,
			"shields": 800,
			"hull": 200,
			"required_crew": 1,
			"bunks": 1,
			"mass": 20,
			"drag": 0.8,
			"heat_dissipation": 0.78,
			"outfit_space": 85,
			"weapon_capacity": 28,
			"engine_capacity": 22
		},
		"description": "The Barb's commercial success spurred demand for a variant equipped with a Proton Gun. Syndicated Systems had to remove the turret mounting hardware to fit the powerful cannon, but the result is a level of short-range firepower that is unheard-of for a craft its size."
	},
	"Barb": {
		"upper": "Barb",
		"lower": "barb",
		"race": "Human",
		"sprite": "ship/barb",
		"attributes": {
			"category": "Fighter",
			"cost": 50000,
			"shields": 800,
			"hull": 200,
			"required_crew": 1,
			"bunks": 2,
			"mass": 20,
			"drag": 0.8,
			"heat_dissipation": 0.78,
			"outfit_space": 85,
			"weapon_capacity": 24,
			"engine_capacity": 22
		},
		"description": "Though the Syndicate doesn't build fighter carriers, it is testing the waters with the Barb, a cheap and flexible carrier-launched craft featuring newly-developed miniaturized ion engines. The design philosophy of the Barb seems to have been uglier than the Protector, and as you look at the cockpit nestled between the massive gun port and turret mount, you wonder where the power systems are supposed to go. Though an awkward-looking ship, it seems flexible enough to become a dangerous addition to any fleet with carriers."
	},
	"Bastion": {
		"upper": "Bastion",
		"lower": "bastion",
		"race": "Human",
		"sprite": "ship/bastion",
		"attributes": {
			"category": "Medium Warship",
			"cost": 3560000,
			"shields": 6700,
			"hull": 4200,
			"required_crew": 32,
			"bunks": 47,
			"mass": 580,
			"drag": 10.3,
			"heat_dissipation": 0.5,
			"fuel_capacity": 500,
			"cargo_space": 110,
			"outfit_space": 470,
			"weapon_capacity": 180,
			"engine_capacity": 120
		},
		"description": "The Southbound Shipyards Bastion is designed as a heavy defense platform to accompany freighter convoys, in addition to having enough cargo capacity to serve as a freighter in its own right. Because of its heavy armament, it is classified as a warship rather than a freighter."
	},
	"Behemoth": {
		"upper": "Behemoth",
		"lower": "behemoth",
		"race": "Human",
		"sprite": "ship/behemoth",
		"attributes": {
			"category": "Heavy Freighter",
			"cost": 10800000,
			"shields": 7600,
			"hull": 6300,
			"required_crew": 12,
			"bunks": 30,
			"mass": 540,
			"drag": 11.7,
			"heat_dissipation": 0.4,
			"fuel_capacity": 600,
			"cargo_space": 490,
			"outfit_space": 510,
			"weapon_capacity": 280,
			"engine_capacity": 90
		},
		"description": "The Behemoth is a recent ship design from Betelgeuse Shipyards, designed as an alternative to the Syndicate Bulk Freighter. Although its cargo capacity is somewhat lower, it is also more maneuverable, and packs a heavier armament by default."
	},
	"Berserker": {
		"upper": "Berserker",
		"lower": "berserker",
		"race": "Human",
		"sprite": "ship/berserker",
		"attributes": {
			"category": "Interceptor",
			"cost": 520000,
			"shields": 2200,
			"hull": 500,
			"required_crew": 1,
			"bunks": 2,
			"mass": 110,
			"drag": 2.2,
			"heat_dissipation": 0.85,
			"fuel_capacity": 400,
			"cargo_space": 10,
			"outfit_space": 200,
			"weapon_capacity": 35,
			"engine_capacity": 65
		},
		"description": "Once one of the most popular interceptor-class ships, the Berserker's popularity is now waning in favor of more modern and versatile ships like the Hawk. Although limited numbers are still produced by Betelgeuse Shipyards, most Berserkers that are in service today are more than half a century old."
	},
	"Blackbird": {
		"upper": "Blackbird",
		"lower": "blackbird",
		"race": "Human",
		"sprite": "ship/blackbird",
		"attributes": {
			"category": "Transport",
			"cost": 2230000,
			"shields": 4400,
			"hull": 900,
			"required_crew": 3,
			"bunks": 28,
			"mass": 220,
			"drag": 5,
			"heat_dissipation": 0.7,
			"fuel_capacity": 700,
			"cargo_space": 60,
			"outfit_space": 350,
			"weapon_capacity": 90,
			"engine_capacity": 110
		},
		"description": "The Tarazed Blackbird is a high-class passenger transport, designed to move large numbers of people across the galaxy with speed and safety. Although not equipped with much weaponry, a Blackbird is well shielded and fast enough to evade pirate attacks, and its cargo capacity is high enough to allow the captain to take courier missions on the side."
	},
	"Bounder": {
		"upper": "Bounder",
		"lower": "bounder",
		"race": "Human",
		"sprite": "ship/bounder",
		"attributes": {
			"category": "Transport",
			"cost": 1140000,
			"shields": 2200,
			"hull": 700,
			"required_crew": 1,
			"bunks": 17,
			"mass": 130,
			"drag": 3.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 900,
			"cargo_space": 40,
			"outfit_space": 220,
			"weapon_capacity": 50,
			"engine_capacity": 110
		},
		"description": "The Megaparsec Bounder is a scout ship and courier, designed not for battle but for carrying passengers and small amounts of cargo across large distances quickly."
	},
	"Boxwing": {
		"upper": "Boxwing",
		"lower": "boxwing",
		"race": "Human",
		"sprite": "ship/boxwing",
		"attributes": {
			"category": "Fighter",
			"cost": 369000,
			"shields": 400,
			"hull": 800,
			"required_crew": 1,
			"bunks": 1,
			"mass": 45,
			"drag": 0.59,
			"heat_dissipation": 0.27,
			"outfit_space": 45,
			"engine_capacity": 28,
			"cargo_space": 80
		},
		"description": "After introducing the Type F cargo pod for the Hauler, it became apparent to merchant captains that the new carriers could offer more flexibility within their fleet, if there were a cargo box they could attach to the fighter arms. Enter the F6-C: Boxwing, the Fighter that doesn't fight, but carries cargo instead. Cargo preservation equipment gives the Boxwing much more mass and very poor heat dissipation characteristics compared to other fighters. That it cannot carry any weapons is only part of the reason jocks call it Flying Coffin amongst themselves; besides the ship resembling one and being very sluggish, the pilot seat doubles as a bunk, and is cramped beyond the comfort level of most. The interactive panoramic window H.U.D. is the only thing that keeps claustrophobic episodes from becoming a major problem."
	},
	"Bulk Freighter": {
		"upper": "Bulk Freighter",
		"lower": "bulk freighter",
		"race": "Human",
		"sprite": "ship/bulk freighter",
		"attributes": {
			"category": "Heavy Freighter",
			"cost": 9400000,
			"shields": 4000,
			"hull": 7600,
			"required_crew": 6,
			"bunks": 18,
			"mass": 870,
			"drag": 15.8,
			"heat_dissipation": 0.5,
			"fuel_capacity": 600,
			"cargo_space": 600,
			"outfit_space": 410,
			"weapon_capacity": 180,
			"engine_capacity": 85
		},
		"description": "The Bulk Freighter is the ultimate cargo ship, able to carry as much cargo as four ordinary Syndicate Freighters. It is also, however, an incredibly slow ship and difficult to maneuver, especially when loaded down with cargo. Some freight caravans use ordinary freighters instead of bulk freighters just to avoid the hassle of constantly having to wait for the Bulk Freighter to properly align itself for hyperspace travel."
	},
	"Carrier": {
		"upper": "Carrier",
		"lower": "carrier",
		"race": "Human",
		"sprite": "ship/carrier",
		"attributes": {
			"category": "Heavy Warship",
			"licenses": {
				"Navy": 1,
				"Carrier": 1
			},
			"cost": 15200000,
			"shields": 21400,
			"hull": 8300,
			"required_crew": 111,
			"bunks": 184,
			"mass": 910,
			"drag": 17.7,
			"heat_dissipation": 0.45,
			"fuel_capacity": 700,
			"cargo_space": 100,
			"outfit_space": 820,
			"weapon_capacity": 370,
			"engine_capacity": 210
		},
		"description": "The Carrier is more than just a warship: it is practically a mobile space station, with docking bays for an entire squadron of drones and fighters and enough crew to fill a small village. Although designed primarily for engaging enemies from a distance, a Carrier can also do significant damage in close combat."
	},
	"Class C Freighter": {
		"upper": "Class C Freighter",
		"lower": "class c freighter",
		"race": "Human",
		"sprite": "ship/bulk freighter",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 11400000,
			"shields": 13500,
			"hull": 7600,
			"required_crew": 18,
			"bunks": 43,
			"mass": 810,
			"drag": 16.4,
			"heat_dissipation": 0.5,
			"fuel_capacity": 600,
			"cargo_space": 20,
			"outfit_space": 400,
			"weapon_capacity": 140,
			"engine_capacity": 85
		},
		"description": "The Class C Freighter is a stealth warship designed by the Syndicate for baiting pirates with the offer of a seemingly helpless, ordinary bulk freighter. Inside, its cargo space has all been converted into drone bays, allowing it to carry a dozen combat drones."
	},
	"Clipper": {
		"upper": "Clipper",
		"lower": "clipper",
		"race": "Human",
		"sprite": "ship/clipper",
		"attributes": {
			"category": "Light Freighter",
			"cost": 900000,
			"shields": 2700,
			"hull": 800,
			"required_crew": 3,
			"bunks": 9,
			"mass": 150,
			"drag": 3.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 500,
			"cargo_space": 70,
			"outfit_space": 260,
			"weapon_capacity": 60,
			"engine_capacity": 80
		},
		"description": "The Clipper is the smaller sister ship to the popular Southbound Shipyards Argosy. Although not able to carry as much cargo, Clippers are versatile ships that can be used as passenger transports, couriers, or even warships in a pinch, and they come with enough free space to be customized based on an individual captain's needs."
	},
	"Combat Drone": {
		"upper": "Combat Drone",
		"lower": "combat drone",
		"race": "Human",
		"sprite": "ship/combat drone",
		"attributes": {
			"category": "Drone",
			"licenses": {
				"Navy": 1
			},
			"cost": 83000,
			"hull": 700,
			"mass": 20,
			"drag": 0.59,
			"heat_dissipation": 0.9,
			"outfit_space": 58,
			"weapon_capacity": 8,
			"engine_capacity": 28,
			"automaton": 1
		},
		"description": "Incorporating new, experimental lightweight materials, the Lionheart Corvette combines the speed and agility of a fighter with the armament of a heavy warship. Its weak hull is more than compensated for by its advanced shielding matrix."
	},
	"Cruiser": {
		"upper": "Cruiser",
		"lower": "cruiser",
		"race": "Human",
		"sprite": "ship/cruiser",
		"attributes": {
			"category": "Heavy Warship",
			"licenses": {
				"Navy": 1,
				"Cruiser": 1
			},
			"cost": 11200000,
			"shields": 19600,
			"hull": 6400,
			"required_crew": 81,
			"bunks": 136,
			"mass": 680,
			"drag": 10.1,
			"heat_dissipation": 0.45,
			"fuel_capacity": 600,
			"cargo_space": 60,
			"outfit_space": 760,
			"weapon_capacity": 320,
			"engine_capacity": 170
		},
		"description": "The Republic Cruiser is a relatively recent design, a much larger version of the Frigate designed to be able to take on an entire pirate fleet if necessary. In addition to a wide variety of weaponry, Cruisers have space to carry four attack drones: fast, pilotless fighters that can be controlled remotely."
	},
	"Dagger": {
		"upper": "Dagger",
		"lower": "dagger",
		"race": "Human",
		"sprite": "ship/dagger",
		"attributes": {
			"category": "Fighter",
			"cost": 129000,
			"shields": 1000,
			"hull": 300,
			"required_crew": 1,
			"bunks": 1,
			"mass": 20,
			"drag": 0.63,
			"heat_dissipation": 0.9,
			"outfit_space": 90,
			"weapon_capacity": 20,
			"engine_capacity": 30
		},
		"description": "The Dagger is a fighter designed by Lionheart Industries, intended to be carried by their Aerie warship, although other ships have been known to carry them, as well. As with many Lionheart ships, its chassis is largely composed of lightweight composite materials, making it considerably faster than other fighters."
	},
	"Deep River Transport": {
		"upper": "Deep River Transport",
		"lower": "deep river transport",
		"race": "Wanderer",
		"sprite": "ship/deep river",
		"attributes": {
			"category": "Heavy Freighter",
			"licenses": {
				"Wanderer": 1
			},
			"cost": 18300000,
			"shields": 17600,
			"hull": 47500,
			"required_crew": 13,
			"bunks": 166,
			"mass": 750,
			"drag": 9.4,
			"heat_dissipation": 0.6,
			"fuel_capacity": 500,
			"cargo_space": 74,
			"outfit_space": 321,
			"weapon_capacity": 114,
			"engine_capacity": 83
		},
		"description": "This is a Deep River freighter that has been converted into a transport ship for refugees."
	},
	"Deep River": {
		"upper": "Deep River",
		"lower": "deep river",
		"race": "Wanderer",
		"sprite": "ship/deep river",
		"attributes": {
			"category": "Heavy Freighter",
			"licenses": {
				"Wanderer": 1
			},
			"cost": 18300000,
			"shields": 17600,
			"hull": 47500,
			"required_crew": 13,
			"bunks": 22,
			"mass": 750,
			"drag": 9.4,
			"heat_dissipation": 0.6,
			"fuel_capacity": 500,
			"cargo_space": 1140,
			"outfit_space": 363,
			"weapon_capacity": 177,
			"engine_capacity": 83
		},
		"description": "The Deep River is a bulk freighter, designed to carry cargo in detachable pods."
	},
	"Derecho": {
		"upper": "Derecho",
		"lower": "derecho",
		"race": "Wanderer",
		"sprite": "ship/derecho",
		"attributes": {
			"category": "Heavy Warship",
			"licenses": {
				"Wanderer_Military": 1
			},
			"cost": 30500000,
			"shields": 53200,
			"hull": 32700,
			"required_crew": 53,
			"bunks": 82,
			"mass": 540,
			"drag": 8.7,
			"heat_dissipation": 0.6,
			"fuel_capacity": 500,
			"cargo_space": 56,
			"outfit_space": 796,
			"weapon_capacity": 342,
			"engine_capacity": 164
		},
		"description": "Like a latent gene waiting to express itself, the knowledge of how to wage war in space has been passed down through hundreds of generations of Wanderers. Based on one of their ancient designs, the Derecho has a mixture of agility and raw firepower that is well-suited to their present, rapidly changing situation."
	},
	"Dreadnought": {
		"upper": "Dreadnought",
		"lower": "dreadnought",
		"race": "Human",
		"sprite": "ship/dreadnought",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 11900000,
			"shields": 18100,
			"hull": 7300,
			"required_crew": 84,
			"bunks": 147,
			"mass": 630,
			"drag": 10.1,
			"heat_dissipation": 0.65,
			"fuel_capacity": 600,
			"cargo_space": 100,
			"outfit_space": 790,
			"weapon_capacity": 360,
			"engine_capacity": 190
		},
		"description": "The Dreadnought is a new warship that was designed by Southbound Shipyards in order to provide a large capital ship for the Free Worlds fleets, something capable of standing up to a Navy Cruiser or even a Carrier."
	},
	"Earth Shaper": {
		"upper": "Earth Shaper",
		"lower": "earth shaper",
		"race": "Wanderer",
		"sprite": "ship/earth shaper",
		"attributes": {
			"category": "Light Freighter",
			"licenses": {
				"Wanderer": 1
			},
			"cost": 500000,
			"hull": 3300,
			"mass": 30,
			"drag": 0.9,
			"heat_dissipation": 0.9,
			"fuel_capacity": 300,
			"cargo_space": 27,
			"outfit_space": 59,
			"engine_capacity": 26,
			"atmosphere_scan": 100,
			"automaton": 1
		},
		"description": "The Earth Shaper is a robotic drone that the Wanderers use for mining, exploring, surveying, and terraforming."
	},
	"Falcon": {
		"upper": "Falcon",
		"lower": "falcon",
		"race": "Human",
		"sprite": "ship/falcon",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 10900000,
			"shields": 12800,
			"hull": 3700,
			"required_crew": 52,
			"bunks": 75,
			"mass": 510,
			"drag": 6.7,
			"heat_dissipation": 0.7,
			"fuel_capacity": 600,
			"cargo_space": 90,
			"outfit_space": 540,
			"weapon_capacity": 240,
			"engine_capacity": 150
		},
		"description": "The Tarazed Falcon is one of the most powerful warships that civilians can buy, a sleeker and more maneuverable alternative to the venerable and somewhat outdated Leviathan."
	},
	"Far Lek 14": {
		"upper": "Far Lek 14",
		"lower": "far lek 14",
		"race": "Korath",
		"sprite": "ship/far lek 14",
		"attributes": {
			"category": "Drone",
			"cost": 573000,
			"shields": 900,
			"hull": 1600,
			"automaton": 1,
			"mass": 26,
			"drag": 0.8,
			"heat_dissipation": 1.1,
			"outfit_space": 65,
			"weapon_capacity": 11,
			"engine_capacity": 24,
			"self_destruct": 0.6,
			"ramscoop": 3
		},
		"description": "At the peak of their recent civil war, the Kor Sestor faction developed these automated attack drones, easy to manufacture and encased in an ultra-dense hull that can absorb a significant amount of damage."
	},
	"Far Osk 27": {
		"upper": "Far Osk 27",
		"lower": "far osk 27",
		"race": "Korath",
		"sprite": "ship/far osk 27",
		"attributes": {
			"category": "Fighter",
			"cost": 761000,
			"shields": 1500,
			"hull": 2400,
			"automaton": 1,
			"mass": 34,
			"drag": 1.1,
			"heat_dissipation": 1,
			"outfit_space": 99,
			"weapon_capacity": 22,
			"engine_capacity": 24,
			"self_destruct": 0.6,
			"ramscoop": 3
		},
		"description": "Because it is piloted by a computer and has no need for a cockpit or life support systems, the FS27 fighter is able to carry far more weaponry than any comparable human ship."
	},
	"Finch": {
		"upper": "Finch",
		"lower": "finch",
		"race": "Human",
		"plural": "Finches",
		"sprite": "ship/finch",
		"attributes": {
			"category": "Fighter",
			"cost": 126000,
			"shields": 1100,
			"hull": 200,
			"required_crew": 1,
			"bunks": 1,
			"mass": 40,
			"drag": 0.83,
			"heat_dissipation": 0.85,
			"outfit_space": 110,
			"weapon_capacity": 20,
			"engine_capacity": 40
		},
		"description": "When the Free Worlds started requesting a Carrier solution from its local shipyards, Tarazed Shipyards quickly saw that a few modifications could make their entry level interceptor into a top tier fighter. Over 85% of the parts that make up the Finch are shared with the Sparrow assembly line, so it's no surprise that even trimmed down to (barely) fit into a fighter bay, the Finch bears strong resemblance to its hyperspace-faring cousin."
	},
	"Firebird": {
		"upper": "Firebird",
		"lower": "firebird",
		"race": "Human",
		"sprite": "ship/firebird",
		"attributes": {
			"category": "Medium Warship",
			"cost": 3700000,
			"shields": 6400,
			"hull": 2800,
			"required_crew": 7,
			"bunks": 22,
			"mass": 290,
			"drag": 4.5,
			"heat_dissipation": 0.6,
			"fuel_capacity": 400,
			"cargo_space": 50,
			"outfit_space": 400,
			"weapon_capacity": 160,
			"engine_capacity": 100
		},
		"description": "The Betelgeuse Shipyards Firebird is a warship with a long and storied past; Firebirds fought on both sides of the Alpha Wars over half a millennium ago, and although the equipment and systems have been upgraded continuously since then, the basic design remains almost the same. The Firebird is also a very rugged ship and easy to repair; supposedly a few of the Firebirds that fought in those wars are still in service today."
	},
	"Flea": {
		"upper": "Flea",
		"lower": "flea",
		"race": "Hai",
		"sprite": "ship/hai flea",
		"attributes": {
			"category": "Drone",
			"cost": 122400,
			"shields": 200,
			"hull": 700,
			"mass": 21,
			"drag": 0.55,
			"heat_dissipation": 0.75,
			"outfit_space": 60,
			"weapon_capacity": 9,
			"engine_capacity": 29,
			"automaton": 1
		},
		"description": "With space for neither cargo nor passengers nor heavy weaponry, the Flivver's only selling point is speed. Flivvers are sold mostly to wealthy individuals who want to be able to travel the stars without needing to share a bunk room on a merchant transport with common people."
	},
	"Flycatcher": {
		"upper": "Flycatcher",
		"lower": "flycatcher",
		"race": "Wanderer",
		"sprite": "ship/flycatcher",
		"attributes": {
			"category": "Drone",
			"licenses": {
				"Wanderer": 1
			},
			"cost": 830000,
			"hull": 4700,
			"mass": 40,
			"drag": 0.6,
			"heat_dissipation": 0.9,
			"outfit_space": 86,
			"weapon_capacity": 28,
			"engine_capacity": 26,
			"automaton": 1
		},
		"description": "Flycatcher drones are used by the Wanderers to keep their star systems safe. Rather than carrying weapons of its own, a stock Flycatcher just carries an anti-missile turret for defending other ships."
	},
	"Freighter": {
		"upper": "Freighter",
		"lower": "freighter",
		"race": "Human",
		"sprite": "ship/freighter",
		"attributes": {
			"category": "Light Freighter",
			"cost": 730000,
			"shields": 2000,
			"hull": 2000,
			"required_crew": 2,
			"bunks": 7,
			"mass": 240,
			"drag": 5.6,
			"heat_dissipation": 0.6,
			"fuel_capacity": 600,
			"cargo_space": 150,
			"outfit_space": 250,
			"weapon_capacity": 80,
			"engine_capacity": 70
		},
		"description": [
			"The Freighter is designed by the Syndicate to be an efficient means of carrying cargo from system to system, but is so slow and difficult to land that most pilots hate flying them.",
			"Freighters are an obvious target for pirates, but turn much too slowly to be able to bring any forward-facing guns to bear on an approaching enemy. As a result, the latest model of freighter is equipped only with turrets, including an anti-missile turret to prevent attackers from simply bombarding them into submission from a safe distance."
		]
	},
	"Frigate": {
		"upper": "Frigate",
		"lower": "frigate",
		"race": "Human",
		"sprite": "ship/frigate",
		"attributes": {
			"category": "Medium Warship",
			"licenses": {
				"Navy": 1
			},
			"cost": 5200000,
			"shields": 8000,
			"hull": 2500,
			"required_crew": 21,
			"bunks": 44,
			"mass": 310,
			"drag": 5.2,
			"heat_dissipation": 0.7,
			"fuel_capacity": 500,
			"cargo_space": 35,
			"outfit_space": 410,
			"weapon_capacity": 170,
			"engine_capacity": 100
		},
		"description": "For centuries, the Frigate was the largest warship produced by the Republic Navy Yard, but now they seem quite small compared to a Cruiser or a Carrier. Armed with a variety of weapons, and with relatively good maneuverability for a ship its size, the Frigate is equally capable at fending off small fighters or bombarding larger ships."
	},
	"Fury": {
		"upper": "Fury",
		"lower": "fury",
		"race": "Human",
		"plural": "Furies",
		"sprite": "ship/fury",
		"attributes": {
			"category": "Interceptor",
			"cost": 490000,
			"shields": 2000,
			"hull": 400,
			"required_crew": 1,
			"bunks": 3,
			"mass": 70,
			"drag": 1.6,
			"heat_dissipation": 0.9,
			"fuel_capacity": 600,
			"cargo_space": 15,
			"outfit_space": 160,
			"weapon_capacity": 40,
			"engine_capacity": 60
		},
		"description": "The Fury is Southbound Shipyard's most popular design of escort ship. They have greater firepower than any other interceptor-class vessel, meaning that any pirate flying solo will think twice before attacking a convoy that is accompanied by a Fury. However, Furies are also much less maneuverable than other small ships."
	},
	"Gascraft": {
		"upper": "Gascraft",
		"lower": "gascraft",
		"race": "Remnant",
		"sprite": "ship/gascraft",
		"attributes": {
			"category": "Transport",
			"cost": 530000,
			"shields": 800,
			"hull": 1500,
			"required_crew": 1,
			"bunks": 1,
			"mass": 80,
			"drag": 1.7,
			"heat_dissipation": 0.9,
			"fuel_capacity": 700,
			"cargo_space": 8,
			"outfit_space": 90,
			"engine_capacity": 34,
			"shield_generation": 0.6,
			"shield_energy": 0.4,
			"hull_repair_rate": 1.2,
			"hull_energy": 0.9,
			"gaslining": 1
		},
		"description": "Centuries ago, the Remnant built these ships in order to explore the upper atmosphere of nearby gas giants. The Archons took issue with the Remnant's research methods, and the studies were unable to be completed. The remaining gascraft have been gathering dust in storage for centuries while the Remnant waits to see if the anger of the Archons will subside."
	},
	"Gunboat": {
		"upper": "Gunboat",
		"lower": "gunboat",
		"race": "Human",
		"sprite": "ship/gunboat",
		"attributes": {
			"category": "Light Warship",
			"licenses": {
				"Navy": 1
			},
			"cost": 3200000,
			"shields": 5800,
			"hull": 1400,
			"required_crew": 7,
			"bunks": 12,
			"mass": 150,
			"drag": 3.1,
			"heat_dissipation": 0.8,
			"fuel_capacity": 600,
			"cargo_space": 50,
			"outfit_space": 270,
			"weapon_capacity": 100,
			"engine_capacity": 90
		},
		"description": "The Navy gunboat is designed for engaging targets at short range, and also serves as the Navy's mobile sensor platform, scanning ships for illegal equipment or cargo."
	},
	"Hauler II": {
		"upper": "Hauler II",
		"lower": "hauler ii",
		"race": "Human",
		"sprite": "ship/hauler ii",
		"attributes": {
			"category": "Heavy Freighter",
			"cost": 2340000,
			"shields": 2900,
			"hull": 5200,
			"required_crew": 3,
			"bunks": 12,
			"mass": 360,
			"drag": 11.5,
			"heat_dissipation": 0.6,
			"fuel_capacity": 400,
			"cargo_space": 260,
			"outfit_space": 350,
			"weapon_capacity": 140,
			"engine_capacity": 80
		},
		"description": "This is a mid-sized freighter, designed for a balance between cargo capacity and defensive capability. Centuries ago, various Hauler models made up nearly half of the merchant vessels in service, but today the design is considered somewhat outdated."
	},
	"Hauler III": {
		"upper": "Hauler III",
		"lower": "hauler iii",
		"race": "Human",
		"sprite": "ship/hauler iii",
		"attributes": {
			"category": "Heavy Freighter",
			"cost": 3260000,
			"shields": 3300,
			"hull": 6700,
			"required_crew": 3,
			"bunks": 12,
			"mass": 470,
			"drag": 12.5,
			"heat_dissipation": 0.6,
			"fuel_capacity": 400,
			"cargo_space": 390,
			"outfit_space": 350,
			"weapon_capacity": 140,
			"engine_capacity": 80
		},
		"description": "Considered by many to be outdated, there are nonetheless many Haulers still in service due to their combination of comparatively low price and simple construction. This large version of the Hauler provides the best tradeoff between price and cargo space."
	},
	"Hauler": {
		"upper": "Hauler",
		"lower": "hauler",
		"race": "Human",
		"sprite": "ship/hauler i",
		"attributes": {
			"category": "Light Freighter",
			"cost": 1430000,
			"shields": 2500,
			"hull": 3700,
			"required_crew": 3,
			"bunks": 12,
			"mass": 250,
			"drag": 10.5,
			"heat_dissipation": 0.6,
			"fuel_capacity": 400,
			"cargo_space": 130,
			"outfit_space": 350,
			"weapon_capacity": 140,
			"engine_capacity": 80
		},
		"description": "Several centuries ago, in the early days of the Republic, the sudden increase in commerce and space travel led to high demand for cargo ships. Haulers were first created simply by bolting a cockpit and engine block onto a cargo container, and the basic design has not changed much since then."
	},
	"Hawk": {
		"upper": "Hawk",
		"lower": "hawk",
		"race": "Human",
		"sprite": "ship/hawk",
		"attributes": {
			"category": "Interceptor",
			"cost": 670000,
			"shields": 2500,
			"hull": 500,
			"required_crew": 2,
			"bunks": 4,
			"mass": 150,
			"drag": 2.1,
			"heat_dissipation": 0.8,
			"fuel_capacity": 300,
			"cargo_space": 30,
			"outfit_space": 200,
			"weapon_capacity": 40,
			"engine_capacity": 70
		},
		"description": "The Tarazed Hawk is an interceptor-class warship often used as an escort for freighters or in a planetary militia's patrol squadron. Hawks are fast enough to chase down most smaller ships, while also being much more heavily armed and armored. They are also, of course, a favorite ship of pirate captains who have earned enough money to afford one."
	},
	"Headhunter": {
		"upper": "Headhunter",
		"lower": "headhunter",
		"race": "Human",
		"sprite": "ship/headhunter",
		"attributes": {
			"category": "Light Warship",
			"cost": 1850000,
			"shields": 3800,
			"hull": 700,
			"required_crew": 2,
			"bunks": 4,
			"mass": 120,
			"drag": 2.6,
			"heat_dissipation": 0.8,
			"fuel_capacity": 400,
			"cargo_space": 50,
			"outfit_space": 250,
			"weapon_capacity": 60,
			"engine_capacity": 80
		},
		"description": "The Headhunter is one of the newest ships designed by Lionheart: a versatile ship that can serve equally well for carrying cargo or for bounty hunting. As with many of Lionheart's designs, the hull is mostly composite fiber rather than metal, sacrificing armor strength for the sake of lighter weight and faster movement."
	},
	"Heavy Shuttle": {
		"upper": "Heavy Shuttle",
		"lower": "heavy shuttle",
		"race": "Human",
		"sprite": "ship/heavy shuttle",
		"attributes": {
			"category": "Transport",
			"cost": 320000,
			"shields": 700,
			"hull": 700,
			"required_crew": 1,
			"bunks": 8,
			"mass": 110,
			"drag": 2.1,
			"heat_dissipation": 0.8,
			"fuel_capacity": 500,
			"cargo_space": 35,
			"outfit_space": 120,
			"weapon_capacity": 10,
			"engine_capacity": 60
		},
		"description": "The Heavy Shuttle is an updated shuttle model from Betelgeuse Shipyards, attempting to improve on their perennial classic by offering slightly better cargo and passenger capacity, at the expense of some speed and maneuverability."
	},
	"Heliarch Interdictor": {
		"upper": "Heliarch Interdictor",
		"lower": "heliarch interdictor",
		"race": "Coalition",
		"sprite": "ship/heliarch interdictor",
		"attributes": {
			"category": "Medium Warship",
			"licenses": {
				"Heliarch": 1
			},
			"cost": 35487000,
			"shields": 65300,
			"hull": 54600,
			"required_crew": 42,
			"bunks": 70,
			"mass": 520,
			"drag": 7.4,
			"heat_dissipation": 0.7,
			"fuel_capacity": 800,
			"cargo_space": 79,
			"outfit_space": 544,
			"weapon_capacity": 179,
			"engine_capacity": 135
		},
		"description": "Anyone who incurs the wrath of the Heliarchs cannot count on making a fast getaway thanks to the Interdictors, which were primarily designed to carry a pair of attractor and repulsor beams that can hold a ship a safe distance away while pushing it around enough to prevent it from getting a hyperspace lock to jump out of the system."
	},
	"Heliarch Neutralizer": {
		"upper": "Heliarch Neutralizer",
		"lower": "heliarch neutralizer",
		"race": "Coalition",
		"sprite": "ship/heliarch neutralizer",
		"attributes": {
			"category": "Light Warship",
			"licenses": {
				"Heliarch": 1
			},
			"cost": 18847000,
			"shields": 36400,
			"hull": 32800,
			"required_crew": 17,
			"bunks": 24,
			"mass": 270,
			"drag": 4.1,
			"heat_dissipation": 0.75,
			"fuel_capacity": 1000,
			"cargo_space": 36,
			"outfit_space": 367,
			"weapon_capacity": 72,
			"engine_capacity": 102
		},
		"description": "The most common Heliarch patrol ship, Neutralizers are designed to be just strong enough to keep an enemy vessel occupied until reinforcements can arrive."
	},
	"Heliarch Punisher": {
		"upper": "Heliarch Punisher",
		"lower": "heliarch punisher",
		"race": "Coalition",
		"sprite": "ship/heliarch punisher",
		"attributes": {
			"category": "Heavy Warship",
			"licenses": {
				"Heliarch": 1
			},
			"cost": 58487000,
			"shields": 108000,
			"hull": 85000,
			"required_crew": 96,
			"bunks": 145,
			"mass": 780,
			"drag": 12.2,
			"heat_dissipation": 0.6,
			"fuel_capacity": 600,
			"cargo_space": 94,
			"outfit_space": 885,
			"weapon_capacity": 324,
			"engine_capacity": 187
		},
		"description": "Although not quite as strong or powerful as the Quarg ships that they are designed to oppose, Heliarch Punishers are versatile and durable ships. Rumors say that the Heliarchs have a small stash of stolen Quarg Skylances that they can outfit the Punishers with in times of war."
	},
	"Hurricane": {
		"upper": "Hurricane",
		"lower": "hurricane",
		"race": "Wanderer",
		"sprite": "ship/hurricane",
		"attributes": {
			"category": "Heavy Warship",
			"licenses": {
				"Wanderer_Military": 1
			},
			"cost": 39100000,
			"shields": 72400,
			"hull": 46500,
			"required_crew": 76,
			"bunks": 117,
			"mass": 770,
			"drag": 11.9,
			"heat_dissipation": 0.55,
			"fuel_capacity": 500,
			"cargo_space": 98,
			"outfit_space": 960,
			"weapon_capacity": 428,
			"engine_capacity": 140
		},
		"description": "The Hurricane is not built for speed, elegance, or versatility, but for one simple purpose: to be durable enough to serve as a rearguard, absorbing an enemy's attacks for long enough to allow the fleet it is guarding to escape."
	},
	"Kar Ik Vot 349": {
		"upper": "Kar Ik Vot 349",
		"lower": "kar ik vot 349",
		"race": "Korath",
		"sprite": "ship/kar ik vot 349",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 41280000,
			"shields": 57200,
			"hull": 65400,
			"automaton": 1,
			"mass": 1350,
			"drag": 16.8,
			"heat_dissipation": 0.5,
			"fuel_capacity": 400,
			"cargo_space": 87,
			"outfit_space": 1054,
			"weapon_capacity": 447,
			"engine_capacity": 173,
			"self_destruct": 0.8,
			"ramscoop": 3
		},
		"description": "The largest and deadliest of the Kor Sestor robotic warships, a single one of these battlecruisers can hold its own against an entire fleet of lesser ships."
	},
	"Kimek Briar": {
		"upper": "Kimek Briar",
		"lower": "kimek briar",
		"race": "Coalition",
		"sprite": "ship/kimek briar",
		"attributes": {
			"category": "Transport",
			"licenses": {
				"Coalition": 1
			},
			"cost": 1532000,
			"shields": 3600,
			"hull": 1700,
			"required_crew": 3,
			"bunks": 25,
			"mass": 180,
			"drag": 3.8,
			"heat_dissipation": 0.75,
			"fuel_capacity": 700,
			"cargo_space": 21,
			"outfit_space": 245,
			"weapon_capacity": 89,
			"engine_capacity": 60
		},
		"description": "With more than twice the population of the Saryds and Arachi combined, the Kimek are constantly in need of transport ships to carry individuals from one world to another."
	},
	"Kimek Spire": {
		"upper": "Kimek Spire",
		"lower": "kimek spire",
		"race": "Coalition",
		"sprite": "ship/kimek spire",
		"attributes": {
			"category": "Transport",
			"licenses": {
				"Coalition": 1
			},
			"cost": 9375000,
			"shields": 14200,
			"hull": 4900,
			"required_crew": 19,
			"bunks": 197,
			"mass": 570,
			"drag": 8.4,
			"heat_dissipation": 0.6,
			"fuel_capacity": 800,
			"cargo_space": 64,
			"outfit_space": 489,
			"weapon_capacity": 256,
			"engine_capacity": 129
		},
		"description": "The Spire is the largest passenger transport in Coalition space, able to carry nearly two hundred individuals... as long as they're comfortable staying in the tiny bunk rooms that are primarily designed to meet the needs of a Kimek. Most of the ceilings are too short for a Saryd to stand up straight, and the beds are too small for an Arach to stretch their legs out comfortably."
	},
	"Kimek Thistle": {
		"upper": "Kimek Thistle",
		"lower": "kimek thistle",
		"race": "Coalition",
		"sprite": "ship/kimek thistle",
		"attributes": {
			"category": "Transport",
			"licenses": {
				"Coalition": 1
			},
			"cost": 2904000,
			"shields": 7500,
			"hull": 2800,
			"required_crew": 7,
			"bunks": 52,
			"mass": 270,
			"drag": 5.8,
			"heat_dissipation": 0.7,
			"fuel_capacity": 700,
			"cargo_space": 29,
			"outfit_space": 321,
			"weapon_capacity": 118,
			"engine_capacity": 87
		},
		"description": "The Kimek love traveling so much that some of them will happily spend months at a time in a transport this size, and the passengers often grow into a tight-knit community by the end of their journeys together."
	},
	"Kimek Thorn": {
		"upper": "Kimek Thorn",
		"lower": "kimek thorn",
		"race": "Coalition",
		"sprite": "ship/kimek thorn",
		"attributes": {
			"category": "Transport",
			"licenses": {
				"Coalition": 1
			},
			"cost": 440000,
			"shields": 1400,
			"hull": 800,
			"required_crew": 1,
			"bunks": 7,
			"mass": 80,
			"drag": 1.8,
			"heat_dissipation": 0.8,
			"fuel_capacity": 600,
			"cargo_space": 12,
			"outfit_space": 133,
			"weapon_capacity": 40,
			"engine_capacity": 38
		},
		"description": "The Thorn is the Kimek equivalent of a shuttle, and thanks to their speed and maneuverability they are used throughout Coalition space for transferring passengers from one ship to another or from a planet into orbit."
	},
	"Korath Chaser": {
		"upper": "Korath Chaser",
		"lower": "korath chaser",
		"race": "Korath",
		"sprite": "ship/chaser",
		"attributes": {
			"category": "Fighter",
			"cost": 671000,
			"shields": 2300,
			"hull": 900,
			"required_crew": 1,
			"bunks": 1,
			"mass": 40,
			"drag": 0.9,
			"heat_dissipation": 0.9,
			"outfit_space": 92,
			"weapon_capacity": 25,
			"engine_capacity": 30
		},
		"description": "The Korath Raider is their warship of choice for plundering neighboring species."
	},
	"Korath World-Ship": {
		"upper": "Korath World-Ship",
		"lower": "korath world-ship",
		"race": "Korath",
		"sprite": "ship/world-ship a",
		"attributes": {
			"category": "Heavy Freighter",
			"cost": 27690000,
			"shields": 47000,
			"hull": 34000,
			"required_crew": 794,
			"bunks": 1492,
			"mass": 1735,
			"drag": 21,
			"heat_dissipation": 0.4,
			"fuel_capacity": 1000,
			"cargo_space": 264,
			"outfit_space": 778,
			"weapon_capacity": 314,
			"engine_capacity": 165
		},
		"description": "Korath World-Ships are massive nomadic habitats that hold all that is left of their people."
	},
	"Lance": {
		"upper": "Lance",
		"lower": "lance",
		"race": "Human",
		"sprite": "ship/lance",
		"attributes": {
			"category": "Fighter",
			"cost": 93000,
			"shields": 800,
			"hull": 400,
			"required_crew": 1,
			"bunks": 1,
			"mass": 30,
			"drag": 0.7,
			"heat_dissipation": 0.8,
			"outfit_space": 100,
			"weapon_capacity": 20,
			"engine_capacity": 30
		},
		"description": "The Lance is the primary fighter used by the Republic Navy. As with all fighters, it is weak by itself but very effective as part of a larger squadron."
	},
	"Leviathan": {
		"upper": "Leviathan",
		"lower": "leviathan",
		"race": "Human",
		"sprite": "ship/leviathan",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 9800000,
			"shields": 14400,
			"hull": 5000,
			"required_crew": 43,
			"bunks": 64,
			"mass": 480,
			"drag": 7.6,
			"heat_dissipation": 0.5,
			"fuel_capacity": 500,
			"cargo_space": 80,
			"outfit_space": 620,
			"weapon_capacity": 240,
			"engine_capacity": 120
		},
		"description": "The Betelgeuse Shipyards Leviathan has been in service since long before the Republic existed. Although considered today to be an outdated and clunky model, it is still a force to be reckoned with."
	},
	"Lightning Bug": {
		"upper": "Lightning Bug",
		"lower": "lightning bug",
		"race": "Hai",
		"sprite": "ship/hai lightning bug",
		"attributes": {
			"category": "Light Warship",
			"cost": 3200000,
			"shields": 6700,
			"hull": 1700,
			"required_crew": 4,
			"bunks": 10,
			"mass": 220,
			"drag": 3.8,
			"heat_dissipation": 0.85,
			"fuel_capacity": 600,
			"cargo_space": 73,
			"outfit_space": 278,
			"weapon_capacity": 87,
			"engine_capacity": 93
		},
		"description": "The Lightning Bug is a small defensive ship, mostly used by the Hai as a convoy escort. In its stock configuration, its only offensive weapon is a single ion cannon."
	},
	"Manta": {
		"upper": "Manta",
		"lower": "manta",
		"race": "Human",
		"sprite": "ship/manta",
		"attributes": {
			"category": "Medium Warship",
			"cost": 3400000,
			"shields": 5900,
			"hull": 1500,
			"required_crew": 6,
			"bunks": 10,
			"mass": 170,
			"drag": 4.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 400,
			"cargo_space": 20,
			"outfit_space": 350,
			"weapon_capacity": 140,
			"engine_capacity": 100
		},
		"description": "After their Quicksilver light warship with its armament of particle cannons became a large success with convoy escorts and planetary defense forces, Megaparsec decided to develop a larger ship with similar maneuverability but heavier firepower. The Manta is the result: a ship with enough long-range firepower that fleeing from a battle with it is almost impossible."
	},
	"Marauder Arrow": {
		"upper": "Marauder Arrow",
		"lower": "marauder arrow",
		"race": "Marauders",
		"sprite": "ship/marrows",
		"attributes": {
			"category": "Interceptor",
			"cost": 1320000,
			"shields": 2300,
			"hull": 500,
			"required_crew": 2,
			"bunks": 5,
			"mass": 145,
			"drag": 2.7,
			"heat_dissipation": 0.85,
			"fuel_capacity": 400,
			"cargo_space": 5,
			"outfit_space": 210,
			"weapon_capacity": 55,
			"engine_capacity": 80,
			"self_destruct": 0.25
		},
		"description": "This Arrow has had numerous modifications to its hull and internal systems to make more room for outfits - mostly with combat in mind. More shields, weapons, engines, outfit space, and a turret mount nearly push this ship into the Light Warship category, and definitely make it one of the heaviest Interceptors you're likely to find."
	},
	"Marauder Bounder": {
		"upper": "Marauder Bounder",
		"lower": "marauder bounder",
		"race": "Marauders",
		"sprite": "ship/mbounders",
		"attributes": {
			"category": "Interceptor",
			"cost": 1250000,
			"shields": 2500,
			"hull": 700,
			"required_crew": 2,
			"bunks": 18,
			"mass": 145,
			"drag": 3.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 900,
			"cargo_space": 20,
			"outfit_space": 240,
			"weapon_capacity": 80,
			"engine_capacity": 115,
			"self_destruct": 0.25
		},
		"description": "This Megaparsec Bounder has been modified from a courier-scout into a heavy escort Interceptor - currently the largest in the class. A little extra outfit space, reinforced turret mounts, a new gun port in front of the pilot, and additional shield emitters bring this former Transport into combat with fearsome speed and armament."
	},
	"Marauder Falcon": {
		"upper": "Marauder Falcon",
		"lower": "marauder falcon",
		"race": "Marauders",
		"sprite": "ship/mfalcons",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 13900000,
			"shields": 14100,
			"hull": 4100,
			"required_crew": 43,
			"bunks": 80,
			"mass": 560,
			"drag": 6.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 600,
			"cargo_space": 60,
			"outfit_space": 580,
			"weapon_capacity": 265,
			"engine_capacity": 165,
			"self_destruct": 0.15
		},
		"description": "This Tarazed Falcon has been heavily modified by some very dedicated craftsmen. The hull is riddled with extra shield emitters and expanded equipment bays, adding bulk and definitely voiding the warranty."
	},
	"Marauder Firebird": {
		"upper": "Marauder Firebird",
		"lower": "marauder firebird",
		"race": "Marauders",
		"sprite": "ship/mfirebirds",
		"attributes": {
			"category": "Medium Warship",
			"cost": 4100000,
			"shields": 7000,
			"hull": 3000,
			"required_crew": 10,
			"bunks": 25,
			"mass": 350,
			"drag": 4.5,
			"heat_dissipation": 0.6,
			"fuel_capacity": 400,
			"cargo_space": 20,
			"outfit_space": 450,
			"weapon_capacity": 175,
			"engine_capacity": 110,
			"self_destruct": 0.25
		},
		"description": "By the looks of the modification that have taken place, you suspect that this ship contains no original parts. With extra shield emitters, hull plating, and outfit space, this half-millennium young ship is finding new life with its heavy modification."
	},
	"Marauder Fury": {
		"upper": "Marauder Fury",
		"lower": "marauder fury",
		"race": "Marauders",
		"plural": "Marauder Furies",
		"sprite": "ship/mfury",
		"attributes": {
			"category": "Interceptor",
			"cost": 750000,
			"shields": 3000,
			"hull": 600,
			"required_crew": 1,
			"bunks": 3,
			"mass": 100,
			"drag": 1.9,
			"heat_dissipation": 0.85,
			"fuel_capacity": 500,
			"cargo_space": 15,
			"outfit_space": 240,
			"weapon_capacity": 80,
			"engine_capacity": 100,
			"ramscoop": 2
		},
		"description": "You're sure there's a Southbound Fury under all the extra modifications. This ship appears to be one man's insane quest to make the most powerful single pilot warship ever. Upon closer inspection, you're inclined to believe he may have succeeded."
	},
	"Marauder Leviathan": {
		"upper": "Marauder Leviathan",
		"lower": "marauder leviathan",
		"race": "Marauders",
		"sprite": "ship/mleviathans",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 10800000,
			"shields": 16000,
			"hull": 5500,
			"required_crew": 48,
			"bunks": 69,
			"mass": 640,
			"drag": 7.6,
			"heat_dissipation": 0.5,
			"fuel_capacity": 500,
			"cargo_space": 40,
			"outfit_space": 680,
			"weapon_capacity": 265,
			"engine_capacity": 140,
			"self_destruct": 0.15
		},
		"description": "The Betelgeuse Shipyards Leviathan has been in service for a long time, and captains have had some very interesting ideas about how to modify them for optimum performance. This one has had the hull surface completely stripped off and replaced with a surface containing more shield projectors per square meter."
	},
	"Marauder Manta": {
		"upper": "Marauder Manta",
		"lower": "marauder manta",
		"race": "Marauders",
		"sprite": "ship/mmantas",
		"attributes": {
			"category": "Medium Warship",
			"cost": 3740000,
			"shields": 6500,
			"hull": 1750,
			"required_crew": 7,
			"bunks": 11,
			"mass": 195,
			"drag": 4.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 400,
			"cargo_space": 10,
			"outfit_space": 390,
			"weapon_capacity": 155,
			"engine_capacity": 110,
			"self_destruct": 0.25
		},
		"description": "After the Syndicate released their Vanguard Heavy Warship, the Manta fell somewhat out of favor, lacking the ability to mount any anti-missile systems. The owner of this Manta rectified that, added some extra armor plating and shield emitters, and rearranged some of the internals to yield a little more outfit space. Dry tonnage alone keeps it in the Medium Warship category."
	},
	"Marauder Quicksilver": {
		"upper": "Marauder Quicksilver",
		"lower": "marauder quicksilver",
		"race": "Marauders",
		"sprite": "ship/mquicksilvers",
		"attributes": {
			"category": "Light Warship",
			"cost": 1200000,
			"shields": 3500,
			"hull": 900,
			"required_crew": 4,
			"bunks": 7,
			"mass": 140,
			"drag": 2.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 400,
			"cargo_space": 5,
			"outfit_space": 265,
			"weapon_capacity": 65,
			"engine_capacity": 75,
			"self_destruct": 0.25
		},
		"description": "This Megaparsec Quicksilver is a bit of a Hotrod, being a little faster, with extra shield projectors, hull plating, and an extra bunk. This aftermarket model also features a turret mount, perhaps in an answer to Lionheart's Headhunter. The shop that built this ship is sure to see more customers."
	},
	"Marauder Raven": {
		"upper": "Marauder Raven",
		"lower": "marauder raven",
		"race": "Marauders",
		"sprite": "ship/mravens",
		"attributes": {
			"category": "Light Warship",
			"cost": 2250000,
			"shields": 5200,
			"hull": 1600,
			"required_crew": 7,
			"bunks": 14,
			"mass": 145,
			"drag": 3.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 500,
			"cargo_space": 20,
			"outfit_space": 310,
			"weapon_capacity": 105,
			"engine_capacity": 110,
			"self_destruct": 0.25
		},
		"description": "The modifier of this Raven has given more heft to an agile and elegant vessel. They've added a turret and some apparently flimsy bulkheads over extra shield emitters and outfit space. If it weren't for the wingtips, you would barely recognize Lionheart's ship under the patchwork that you expect has made an already deadly warship even more so."
	},
	"Marauder Splinter": {
		"upper": "Marauder Splinter",
		"lower": "marauder splinter",
		"race": "Marauders",
		"sprite": "ship/msplinters",
		"attributes": {
			"category": "Medium Warship",
			"cost": 3400000,
			"shields": 5700,
			"hull": 1950,
			"required_crew": 14,
			"bunks": 22,
			"mass": 275,
			"drag": 4,
			"heat_dissipation": 0.7,
			"fuel_capacity": 600,
			"cargo_space": 40,
			"outfit_space": 450,
			"weapon_capacity": 165,
			"engine_capacity": 110,
			"self_destruct": 0.25
		},
		"description": "The Splinter is the largest warship produced by Megaparsec. Apparently someone wanted a bit more out of it, and has covered large sections of the hull with extra shield emitters and hull plating. Much of the stock cargo space has been converted to outfit, weapons and engines space, coupled with streamlining of existing internal systems make this light Medium Warship an agile and flexible war machine."
	},
	"Met Par Tek 53": {
		"upper": "Met Par Tek 53",
		"lower": "met par tek 53",
		"race": "Korath",
		"sprite": "ship/met par tek 53",
		"attributes": {
			"category": "Light Warship",
			"cost": 14480000,
			"shields": 15100,
			"hull": 22200,
			"automaton": 1,
			"mass": 420,
			"drag": 5.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 400,
			"cargo_space": 26,
			"outfit_space": 610,
			"weapon_capacity": 213,
			"engine_capacity": 110,
			"self_destruct": 0.65,
			"ramscoop": 3
		},
		"description": "Although this is the smallest Kor Sestor ship other than their fighters, it is larger than most human capital ships and considerably more powerful."
	},
	"Model 8": {
		"upper": "Model 8",
		"lower": "model 8",
		"race": "Korath",
		"sprite": "ship/model 8",
		"attributes": {
			"category": "Interceptor",
			"cost": 3725000,
			"shields": 5450,
			"hull": 3320,
			"automaton": 1,
			"mass": 110,
			"drag": 3.2,
			"heat_dissipation": 1.5,
			"fuel_capacity": 200,
			"cargo_space": 29,
			"outfit_space": 220,
			"weapon_capacity": 49,
			"engine_capacity": 60,
			"self_destruct": 0.6,
			"ramscoop": 3
		},
		"description": "The primary role of the smallest Kor Mereti drones is asteroid mining, but their lasers can also be employed as offensive weapons when necessary."
	},
	"Model 16": {
		"upper": "Model 16",
		"lower": "model 16",
		"race": "Korath",
		"sprite": "ship/model 16",
		"attributes": {
			"category": "Light Warship",
			"cost": 8449000,
			"shields": 15700,
			"hull": 9800,
			"automaton": 1,
			"mass": 250,
			"drag": 6.9,
			"heat_dissipation": 1.3,
			"fuel_capacity": 400,
			"cargo_space": 7,
			"outfit_space": 426,
			"weapon_capacity": 149,
			"engine_capacity": 107,
			"self_destruct": 0.65,
			"ramscoop": 3
		},
		"description": "The Kor Mereti war drones are constructed in a modular fashion, which allows them to grow over time as more materials become available. This one is recently built, and relatively small."
	},
	"Model 32": {
		"upper": "Model 32",
		"lower": "model 32",
		"race": "Korath",
		"sprite": "ship/model 32",
		"attributes": {
			"category": "Light Warship",
			"cost": 12765000,
			"shields": 27900,
			"hull": 13400,
			"automaton": 1,
			"mass": 370,
			"drag": 9,
			"heat_dissipation": 1.3,
			"fuel_capacity": 400,
			"cargo_space": 16,
			"outfit_space": 481,
			"weapon_capacity": 205,
			"engine_capacity": 110,
			"self_destruct": 0.7,
			"ramscoop": 3
		},
		"description": "The Kor Mereti built their drones to mimic life: capable of growth and development throughout their life cycles. Their automated factories can convert the drones from one configuration to another by adding or removing modules."
	},
	"Model 64": {
		"upper": "Model 64",
		"lower": "model 64",
		"race": "Korath",
		"sprite": "ship/model 64",
		"attributes": {
			"category": "Medium Warship",
			"cost": 19552000,
			"shields": 41700,
			"hull": 18000,
			"automaton": 1,
			"mass": 580,
			"drag": 11.1,
			"heat_dissipation": 1.1,
			"fuel_capacity": 400,
			"cargo_space": 34,
			"outfit_space": 567,
			"weapon_capacity": 263,
			"engine_capacity": 114,
			"self_destruct": 0.74,
			"ramscoop": 3
		},
		"description": "This medium-sized drone serves the Kor Mereti fleets in much the same way as a human Frigate, but in terms of total firepower it is far beyond anything humans have constructed."
	},
	"Model 128": {
		"upper": "Model 128",
		"lower": "model 128",
		"race": "Korath",
		"sprite": "ship/model 128",
		"attributes": {
			"category": "Medium Warship",
			"cost": 24073000,
			"shields": 57000,
			"hull": 23100,
			"automaton": 1,
			"mass": 780,
			"drag": 13.2,
			"heat_dissipation": 1,
			"fuel_capacity": 400,
			"cargo_space": 53,
			"outfit_space": 713,
			"weapon_capacity": 344,
			"engine_capacity": 132,
			"self_destruct": 0.77,
			"ramscoop": 3
		},
		"description": "As Kor Mereti drones continue to grow and develop into their final form, they split down the middle. At the same time, their shielding and weaponry continue to become stronger."
	},
	"Model 256": {
		"upper": "Model 256",
		"lower": "model 256",
		"race": "Korath",
		"sprite": "ship/model 256",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 34920000,
			"shields": 71700,
			"hull": 28700,
			"automaton": 1,
			"mass": 970,
			"drag": 15.3,
			"heat_dissipation": 0.9,
			"fuel_capacity": 400,
			"cargo_space": 78,
			"outfit_space": 857,
			"weapon_capacity": 393,
			"engine_capacity": 145,
			"self_destruct": 0.79,
			"ramscoop": 3
		},
		"description": "There is a saying among the Quarg that every species which insists on studying war will eventually construct a weapon that outlives its creators. For the Korath, their war drones have very nearly done so."
	},
	"Model 512": {
		"upper": "Model 512",
		"lower": "model 512",
		"race": "Korath",
		"sprite": "ship/model 512",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 40375000,
			"shields": 86400,
			"hull": 34200,
			"automaton": 1,
			"mass": 1150,
			"drag": 17.4,
			"heat_dissipation": 0.8,
			"fuel_capacity": 400,
			"cargo_space": 107,
			"outfit_space": 994,
			"weapon_capacity": 440,
			"engine_capacity": 161,
			"self_destruct": 0.8,
			"ramscoop": 3
		},
		"description": "This is the final state in the evolution of a Kor Mereti war drone: a perfect ring, with incredibly powerful shields and turrets firing in every direction."
	},
	"Modified Argosy": {
		"upper": "Modified Argosy",
		"lower": "modified argosy",
		"race": "Human",
		"plural": "Modified Argosies",
		"sprite": "ship/modified argosy",
		"attributes": {
			"category": "Light Warship",
			"cost": 1960000,
			"shields": 4800,
			"hull": 1900,
			"required_crew": 5,
			"bunks": 12,
			"mass": 250,
			"drag": 6.2,
			"heat_dissipation": 0.6,
			"fuel_capacity": 400,
			"cargo_space": 60,
			"outfit_space": 340,
			"weapon_capacity": 140,
			"engine_capacity": 80
		},
		"description": "The Argosy has long been a favorite ship for pirates, who have come up with many tricks for modifying them to be more suitable as warships."
	},
	"Mule": {
		"upper": "Mule",
		"lower": "mule",
		"race": "Human",
		"sprite": "ship/mule",
		"attributes": {
			"category": "Medium Warship",
			"cost": 4580000,
			"shields": 5400,
			"hull": 4400,
			"required_crew": 6,
			"bunks": 43,
			"mass": 320,
			"drag": 5.7,
			"heat_dissipation": 0.5,
			"fuel_capacity": 600,
			"cargo_space": 270,
			"outfit_space": 450,
			"weapon_capacity": 210,
			"engine_capacity": 110
		},
		"description": "The Mule is as much of a hodgepodge as its looks suggest. The Lionheart ship designers combined a good deal of cargo space with a decent amount of weaponry and even a fighter bay, and ended up with a ship that is mostly used as a freighter but must be classified as a warship because of its heavy armament and shields."
	},
	"Nest": {
		"upper": "Nest",
		"lower": "nest",
		"race": "Human",
		"sprite": "ship/nest",
		"attributes": {
			"category": "Medium Warship",
			"cost": 2500000,
			"shields": 2500,
			"hull": 3700,
			"required_crew": 5,
			"bunks": 14,
			"mass": 250,
			"drag": 10.5,
			"heat_dissipation": 0.67,
			"fuel_capacity": 500,
			"cargo_space": 40,
			"outfit_space": 400,
			"weapon_capacity": 140,
			"engine_capacity": 80
		},
		"description": "Southbound Shipyards quickly answered the Free Worlds' call for a carrier by building modified cargo containers for Haulers - adding a pair of Fighter docking arms, some additional outfit space, and even a couple of bunks. Access to the fighters from within the ship is so inconvenient that most pilots opt to just stay aboard their fighters when in flight. While the technical name for this ship is Hauler I: Type F, Southbound assembly workers started calling the single container variant the Nest due to its complement of Finch Fighters, and the name stuck."
	},
	"Osprey": {
		"upper": "Osprey",
		"lower": "osprey",
		"race": "Human",
		"sprite": "ship/osprey",
		"attributes": {
			"category": "Medium Warship",
			"cost": 4400000,
			"shields": 7200,
			"hull": 1600,
			"required_crew": 9,
			"bunks": 24,
			"mass": 270,
			"drag": 6.1,
			"heat_dissipation": 0.8,
			"fuel_capacity": 600,
			"cargo_space": 40,
			"outfit_space": 450,
			"weapon_capacity": 180,
			"engine_capacity": 130
		},
		"description": "After the Blackbird gained surprising popularity as an agile light warship despite its original design as a transport, Tarazed decided to produce a new design specifically intended as a warship. The Osprey was the result. Although it is considered overpriced by most savvy pilots, it is nevertheless a perennial favorite among those who have the extra cash to spend on it."
	},
	"Pond Strider": {
		"upper": "Pond Strider",
		"lower": "pond strider",
		"race": "Hai",
		"sprite": "ship/hai pond strider",
		"attributes": {
			"category": "Medium Warship",
			"cost": 5250000,
			"shields": 10000,
			"hull": 3000,
			"required_crew": 9,
			"bunks": 18,
			"mass": 132,
			"drag": 3.6,
			"heat_dissipation": 0.65,
			"fuel_capacity": 300,
			"cargo_space": 71,
			"outfit_space": 354,
			"weapon_capacity": 129,
			"engine_capacity": 76
		},
		"drone": [
			"-70 -45 left under",
			"70 -45 right under",
			"-70 28 left under",
			"70 28 right under",
			"-70 -45 over",
			"70 -45 over",
			"-70 28 over",
			"70 28 over"
		],
		"description": "This short range drone carrier was built by the Hai to contain the increasingly aggressive Unfettered with their new Solifuge and Violin Spider ships. The Hai's greater value for life is evident in the remotely-piloted robotic fighter craft, preferring to keep valuable pilots out of harm's way."
	},
	"Protector": {
		"upper": "Protector",
		"lower": "protector",
		"race": "Human",
		"sprite": "ship/protector",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 5500000,
			"shields": 9500,
			"hull": 6500,
			"required_crew": 30,
			"bunks": 69,
			"mass": 500,
			"drag": 10.3,
			"heat_dissipation": 0.6,
			"fuel_capacity": 400,
			"cargo_space": 50,
			"outfit_space": 570,
			"weapon_capacity": 220,
			"engine_capacity": 100
		},
		"description": "Voted the ugliest ship in the sky by Stars and Starships Magazine, the Protector is a typical example of brutally efficient Syndicate engineering. It is basically nothing more than six blaster turrets attached to a set of engines and crew's quarters, designed as a defense platform that can accompany merchant convoys."
	},
	"Pug Arfecta": {
		"upper": "Pug Arfecta",
		"lower": "pug arfecta",
		"race": "Pug",
		"sprite": "ship/pug arfecta",
		"attributes": {
			"category": "Medium Warship",
			"cost": 90000000,
			"shields": 98000,
			"hull": 80000,
			"required_crew": 36,
			"bunks": 46,
			"mass": 670,
			"drag": 7.5,
			"heat_dissipation": 0.8,
			"fuel_capacity": 1200,
			"cargo_space": 64,
			"outfit_space": 640,
			"weapon_capacity": 390,
			"engine_capacity": 220,
			"energy_generation": 200,
			"shield_generation": 32,
			"shield_energy": 32,
			"hull_repair_rate": 5,
			"hull_energy": 5,
			"heat_generation": 10,
			"energy_capacity": 10000,
			"cloaking_fuel": -0.2
		},
		"description": "This is a Pug tier 3 warship, intended for use in combat against either a species on par with the Quarg, or a lesser species that has decided to be particularly meddlesome."
	},
	"Pug Enfolta": {
		"upper": "Pug Enfolta",
		"lower": "pug enfolta",
		"race": "Pug",
		"sprite": "ship/pug enfolta",
		"attributes": {
			"category": "Medium Warship",
			"cost": 6300000,
			"shields": 6800,
			"hull": 1700,
			"required_crew": 19,
			"bunks": 27,
			"mass": 410,
			"drag": 5.9,
			"heat_dissipation": 0.7,
			"fuel_capacity": 600,
			"cargo_space": 40,
			"outfit_space": 360,
			"weapon_capacity": 184,
			"engine_capacity": 106,
			"energy_generation": 22,
			"shield_generation": 8,
			"shield_energy": 8,
			"heat_generation": 32,
			"energy_capacity": 2000
		},
		"description": "This is a medium-sized Pug warship."
	},
	"Pug Maboro": {
		"upper": "Pug Maboro",
		"lower": "pug maboro",
		"race": "Pug",
		"sprite": "ship/pug maboro",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 9500000,
			"shields": 12600,
			"hull": 2700,
			"required_crew": 54,
			"bunks": 87,
			"mass": 940,
			"drag": 9.8,
			"heat_dissipation": 0.6,
			"fuel_capacity": 600,
			"cargo_space": 70,
			"outfit_space": 560,
			"weapon_capacity": 309,
			"engine_capacity": 148,
			"energy_generation": 32,
			"shield_generation": 10,
			"shield_energy": 10,
			"heat_generation": 48,
			"energy_capacity": 4000
		},
		"description": "This is the largest Pug warship."
	},
	"Pug Zibruka": {
		"upper": "Pug Zibruka",
		"lower": "pug zibruka",
		"race": "Pug",
		"sprite": "ship/pug zibruka",
		"attributes": {
			"category": "Light Warship",
			"cost": 1900000,
			"shields": 4000,
			"hull": 1000,
			"required_crew": 4,
			"bunks": 6,
			"mass": 240,
			"drag": 3.1,
			"heat_dissipation": 0.8,
			"fuel_capacity": 600,
			"cargo_space": 20,
			"outfit_space": 180,
			"weapon_capacity": 68,
			"engine_capacity": 76,
			"energy_generation": 10,
			"shield_generation": 6,
			"shield_energy": 6,
			"heat_generation": 20,
			"energy_capacity": 1000
		},
		"description": "The Zibruka is the smallest Pug ship that you know of."
	},
	"Quarg Skylark": {
		"upper": "Quarg Skylark",
		"lower": "quarg skylark",
		"race": "Quarg",
		"sprite": "ship/skylark",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 5900000,
			"shields": 120000,
			"hull": 70000,
			"required_crew": 120,
			"bunks": 210,
			"mass": 460,
			"drag": 12.3,
			"heat_dissipation": 0.7,
			"fuel_capacity": 1000,
			"ramscoop": 10,
			"cargo_space": 200,
			"outfit_space": 600,
			"weapon_capacity": 200,
			"engine_capacity": 120,
			"energy_generation": 80
		},
		"description": "The Skylark is used by the Quarg as a freighter and warship."
	},
	"Quarg Wardragon": {
		"upper": "Quarg Wardragon",
		"lower": "quarg wardragon",
		"race": "Quarg",
		"sprite": "ship/wardragon",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 5900000,
			"shields": 160000,
			"hull": 50000,
			"required_crew": 160,
			"bunks": 185,
			"mass": 360,
			"drag": 9.3,
			"heat_dissipation": 0.5,
			"fuel_capacity": 800,
			"ramscoop": 10,
			"cargo_space": 50,
			"outfit_space": 600,
			"weapon_capacity": 200,
			"engine_capacity": 120,
			"energy_generation": 80
		},
		"description": "The Wardragon is used by the Quarg as a light warship."
	},
	"Quicksilver": {
		"upper": "Quicksilver",
		"lower": "quicksilver",
		"race": "Human",
		"sprite": "ship/quicksilver",
		"attributes": {
			"category": "Light Warship",
			"cost": 1090000,
			"shields": 3000,
			"hull": 800,
			"required_crew": 3,
			"bunks": 6,
			"mass": 120,
			"drag": 2.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 400,
			"cargo_space": 10,
			"outfit_space": 240,
			"weapon_capacity": 60,
			"engine_capacity": 70
		},
		"description": "The Megaparsec Quicksilver is a warship built around a single concept: to design the smallest and fastest ship capable of carrying two particle cannons. Because of its speed and long weapons range, the Quicksilver can keep a safe distance from most targets and bombard them with particle bursts until they are destroyed."
	},
	"Rainmaker": {
		"upper": "Rainmaker",
		"lower": "rainmaker",
		"race": "Human",
		"sprite": "ship/rainmaker",
		"attributes": {
			"category": "Light Warship",
			"licenses": {
				"Navy": 1
			},
			"cost": 1580000,
			"shields": 3500,
			"hull": 1200,
			"required_crew": 7,
			"bunks": 14,
			"mass": 180,
			"drag": 3.8,
			"heat_dissipation": 0.6,
			"fuel_capacity": 500,
			"cargo_space": 25,
			"outfit_space": 230,
			"weapon_capacity": 60,
			"engine_capacity": 50
		},
		"description": "The Rainmaker is a missile boat built in the Republic Navy Yard. It comes equipped with four missile launchers and enough ammunition to destroy even ships many times its size. Because of their lack of maneuverability and relatively light shielding, Rainmakers serve best as long-range attack ships, and once their missile supply is spent, they are relatively useless in combat."
	},
	"Raven": {
		"upper": "Raven",
		"lower": "raven",
		"race": "Human",
		"sprite": "ship/raven",
		"attributes": {
			"category": "Light Warship",
			"cost": 1800000,
			"shields": 4700,
			"hull": 1400,
			"required_crew": 6,
			"bunks": 13,
			"mass": 130,
			"drag": 3.7,
			"heat_dissipation": 0.8,
			"fuel_capacity": 500,
			"cargo_space": 30,
			"outfit_space": 280,
			"weapon_capacity": 90,
			"engine_capacity": 100
		},
		"description": "The Lionheart Raven is their most popular warship, an agile and elegant vessel that can nevertheless deal out and absorb considerable damage. Ravens are a favorite ship for bounty hunters, because they are more than a match for pirate interceptors and can be used by a skilled pilot to take down much larger ships as well."
	},
	"Roost": {
		"upper": "Roost",
		"lower": "roost",
		"race": "Human",
		"sprite": "ship/roost",
		"attributes": {
			"category": "Medium Warship",
			"cost": 3000000,
			"shields": 2900,
			"hull": 5200,
			"required_crew": 7,
			"bunks": 16,
			"mass": 360,
			"drag": 11.5,
			"heat_dissipation": 0.67,
			"fuel_capacity": 600,
			"cargo_space": 80,
			"outfit_space": 450,
			"weapon_capacity": 140,
			"engine_capacity": 80
		},
		"description": "Southbound Shipyards' new fighter-carrying containers have created a new use for what many considered an outdated design. Four external fighter bays make this the biggest civilian carrier on the market, if a little awkward as a warship. After Southbound assembly workers successfully named the Nest, Hauler II: Type F was quickly dubbed the Roost to continue the theme."
	},
	"Saryd Runabout": {
		"upper": "Saryd Runabout",
		"lower": "saryd runabout",
		"race": "Coalition",
		"sprite": "ship/saryd runabout",
		"attributes": {
			"category": "Light Freighter",
			"licenses": {
				"Coalition": 1
			},
			"cost": 942000,
			"shields": 2000,
			"hull": 1400,
			"required_crew": 2,
			"bunks": 13,
			"mass": 140,
			"drag": 2.8,
			"heat_dissipation": 0.7,
			"fuel_capacity": 400,
			"cargo_space": 42,
			"outfit_space": 172,
			"weapon_capacity": 44,
			"engine_capacity": 42
		},
		"description": "Saryds place high value both on solitude, but also on community and collaboration. So, it is not surprising that their smallest spacefaring vessel requires a team of at least two individuals to operate it. It is quite common for a lone Saryd to take on a Kimek or Arach copilot as a way of building cross-species friendships."
	},
	"Saryd Sojourner": {
		"upper": "Saryd Sojourner",
		"lower": "saryd sojourner",
		"race": "Coalition",
		"sprite": "ship/saryd sojourner",
		"attributes": {
			"category": "Heavy Freighter",
			"licenses": {
				"Coalition": 1
			},
			"cost": 11075000,
			"shields": 13000,
			"hull": 7700,
			"required_crew": 17,
			"bunks": 84,
			"mass": 640,
			"drag": 12.9,
			"heat_dissipation": 0.5,
			"fuel_capacity": 800,
			"cargo_space": 260,
			"outfit_space": 568,
			"weapon_capacity": 202,
			"engine_capacity": 156
		},
		"description": "When the first wars were fought against the Quarg, the Saryds had been spacefaring for more than ten thousand Earth years, and their starship technology was considerably more advanced than the Kimek or the Arachi. At that time, ships similar to the modern Sojourner were the most powerful capital ships in the Coalition fleet."
	},
	"Saryd Traveler": {
		"upper": "Saryd Traveler",
		"lower": "saryd traveler",
		"race": "Coalition",
		"sprite": "ship/saryd traveler",
		"attributes": {
			"category": "Heavy Freighter",
			"licenses": {
				"Coalition": 1
			},
			"cost": 3385000,
			"shields": 6500,
			"hull": 4000,
			"required_crew": 10,
			"bunks": 45,
			"mass": 350,
			"drag": 5.5,
			"heat_dissipation": 0.6,
			"fuel_capacity": 600,
			"cargo_space": 137,
			"outfit_space": 466,
			"weapon_capacity": 177,
			"engine_capacity": 79
		},
		"description": "Travelers were originally designed as science vessels, thousands of years ago before the Saryds had catalogued all the life forms and physical phenomena of every world in Coalition space. Today, many Saryd communities still choose to live in a Traveler and journey together from system to system rather than putting down roots on a planet."
	},
	"Saryd Visitor": {
		"upper": "Saryd Visitor",
		"lower": "saryd visitor",
		"race": "Coalition",
		"sprite": "ship/saryd visitor",
		"attributes": {
			"category": "Light Freighter",
			"licenses": {
				"Coalition": 1
			},
			"cost": 1982000,
			"shields": 4000,
			"hull": 2400,
			"required_crew": 5,
			"bunks": 29,
			"mass": 270,
			"drag": 4.4,
			"heat_dissipation": 0.65,
			"fuel_capacity": 400,
			"cargo_space": 98,
			"outfit_space": 320,
			"weapon_capacity": 90,
			"engine_capacity": 57
		},
		"description": "Rather than specializing in carrying passengers or carrying cargo, Saryds seek to make their ships as well-balanced and versatile as possible. As a result, the crew of a typical Visitor can count on performing a different sort of job every week."
	},
	"Scout": {
		"upper": "Scout",
		"lower": "scout",
		"race": "Human",
		"sprite": "ship/scout",
		"attributes": {
			"category": "Transport",
			"cost": 850000,
			"shields": 1200,
			"hull": 400,
			"required_crew": 2,
			"bunks": 12,
			"mass": 110,
			"drag": 3.4,
			"heat_dissipation": 0.7,
			"fuel_capacity": 800,
			"cargo_space": 55,
			"outfit_space": 220,
			"weapon_capacity": 40,
			"engine_capacity": 100
		},
		"description": "The Lionheart Scoutship was designed back in the days when the galaxy was more sparsely populated, and ships prospecting for habitable worlds or worlds rich in resources would often travel far away from any habitable ports where they would be able to refuel. Although the galaxy has now been much more thoroughly explored, the Scout remains a popular ship for long-distance travel."
	},
	"Shield Beetle": {
		"upper": "Shield Beetle",
		"lower": "shield beetle",
		"race": "Hai",
		"sprite": "ship/hai shield beetle",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 17900000,
			"shields": 32000,
			"hull": 9800,
			"required_crew": 47,
			"bunks": 95,
			"mass": 650,
			"drag": 8.8,
			"heat_dissipation": 0.6,
			"fuel_capacity": 500,
			"cargo_space": 142,
			"outfit_space": 798,
			"weapon_capacity": 333,
			"engine_capacity": 150
		},
		"description": "The Shield Beetle is a versatile warship used by the Hai to guard their merchant convoys."
	},
	"Shuttle": {
		"upper": "Shuttle",
		"lower": "shuttle",
		"race": "Human",
		"sprite": "ship/shuttle=0",
		"attributes": {
			"category": "Transport",
			"cost": 180000,
			"shields": 500,
			"hull": 600,
			"required_crew": 1,
			"bunks": 6,
			"mass": 70,
			"drag": 1.7,
			"heat_dissipation": 0.7,
			"fuel_capacity": 400,
			"cargo_space": 20,
			"outfit_space": 120,
			"weapon_capacity": 10,
			"engine_capacity": 60
		},
		"description": [
			"Although Betelgeuse Shipyards produces other ship models as well, the majority of their profits come from sales of the Shuttle. This versatile ship serves equally well as a passenger transport or a cargo courier. It also happens to be the cheapest ship you can buy which is capable of hyperspace travel.",
			"Shuttles are not designed to withstand combat of any sort, but they are fast and maneuverable enough to get out of harm's way if attacked by a larger, slower ship. Although they are typically unarmed, they have enough space for one weapon, which is the origin of the popular phrase, as useless as a blaster cannon on a shuttlecraft."
		]
	},
	"Skein": {
		"upper": "Skein",
		"lower": "skein",
		"race": "Human",
		"sprite": "ship/skein",
		"attributes": {
			"category": "Medium Warship",
			"licenses": {
				"Militia_Carrier": 1
			},
			"cost": 3500000,
			"shields": 3300,
			"hull": 6700,
			"required_crew": 7,
			"bunks": 18,
			"mass": 470,
			"drag": 12.5,
			"heat_dissipation": 0.71,
			"fuel_capacity": 700,
			"cargo_space": 120,
			"outfit_space": 500,
			"weapon_capacity": 140,
			"engine_capacity": 80
		},
		"description": "This particular cockpit and engine set has found itself attached to three of Southbound Shipyards' new Type F Fighter-carrier pods. When the Free Worlds asked for a carrier, they did not expect one that would be able to carry more fighters than even the heaviest Navy warships. Given this fact, the Free Worlds have asked Southbound and Tarazed to restrict sale of the Hauler III: Type F, Skein to its Militia only."
	},
	"Solifuge": {
		"upper": "Solifuge",
		"lower": "solifuge",
		"race": "Hai",
		"sprite": "ship/hai solifuge",
		"attributes": {
			"category": "Heavy Warship",
			"licenses": {
				"Unfettered_Militia": 1
			},
			"cost": 22800000,
			"shields": 37800,
			"hull": 11000,
			"required_crew": 62,
			"bunks": 118,
			"mass": 925,
			"drag": 15.4,
			"heat_dissipation": 0.42,
			"fuel_capacity": 600,
			"cargo_space": 142,
			"outfit_space": 828,
			"weapon_capacity": 342,
			"engine_capacity": 166
		},
		"description": "Impressed by the Alpha's Giftbringer, the Unfettered endeavoured to build their own fighter carrier to take more advantage of their supply of Jump Drives."
	},
	"Sparrow": {
		"upper": "Sparrow",
		"lower": "sparrow",
		"race": "Human",
		"sprite": "ship/sparrow",
		"attributes": {
			"category": "Interceptor",
			"cost": 225000,
			"shields": 1200,
			"hull": 300,
			"required_crew": 1,
			"bunks": 2,
			"mass": 50,
			"drag": 1,
			"heat_dissipation": 0.8,
			"fuel_capacity": 300,
			"cargo_space": 15,
			"outfit_space": 130,
			"weapon_capacity": 20,
			"engine_capacity": 40
		},
		"description": [
			"Classified as an interceptor rather than a fighter because it has its own hyperdrive instead of needing to be carried inside a larger ship, the Tarazed Sparrow is the smallest and cheapest combat ship available. Because of its limited cargo and passenger space, the primary way for a Sparrow pilot to pay the bills is by hunting pirates... or by becoming one. In either case, it is a perilous way to earn a living.",
			"Insurance reports indicate that as many as two out of every three first-time ship buyers who choose to pilot a Sparrow lose their ship (and often, their life as well) within the first month of owning it."
		]
	},
	"Splinter": {
		"upper": "Splinter",
		"lower": "splinter",
		"race": "Human",
		"sprite": "ship/splinter",
		"attributes": {
			"category": "Medium Warship",
			"cost": 3100000,
			"shields": 5200,
			"hull": 1700,
			"required_crew": 12,
			"bunks": 21,
			"mass": 250,
			"drag": 4,
			"heat_dissipation": 0.7,
			"fuel_capacity": 600,
			"cargo_space": 75,
			"outfit_space": 400,
			"weapon_capacity": 150,
			"engine_capacity": 100
		},
		"description": "The Splinter is the largest warship produced by the Megaparsec shipyard. It is designed to be faster and more maneuverable than other ships of a similar size, in order to serve as a heavy escort ship or as part of a planetary defense and patrol fleet. Because of its intended use in merchant convoys, it also has a fair amount of cargo space."
	},
	"Star Barge": {
		"upper": "Star Barge",
		"lower": "star barge",
		"race": "Human",
		"sprite": "ship/star barge",
		"attributes": {
			"category": "Light Freighter",
			"cost": 210000,
			"shields": 600,
			"hull": 1000,
			"required_crew": 1,
			"bunks": 3,
			"mass": 70,
			"drag": 2.4,
			"heat_dissipation": 0.7,
			"fuel_capacity": 300,
			"cargo_space": 50,
			"outfit_space": 130,
			"weapon_capacity": 20,
			"engine_capacity": 40
		},
		"description": [
			"The Syndicate CT-50 Star Barge is little more than a cluster of cargo containers with an engine at one end and a cockpit on the other. It is a slow and ugly ship, but it can carry enough cargo to earn its captain a steady income even in parts of the galaxy where it is hard to find passengers to carry or courier missions.",
			"Because they often carry valuable cargo, and because they are too slow to evade any attackers, Star Barges are a common target of pirates."
		]
	},
	"Star Queen": {
		"upper": "Star Queen",
		"lower": "star queen",
		"race": "Human",
		"sprite": "ship/star queen",
		"attributes": {
			"category": "Transport",
			"cost": 5500000,
			"shields": 4100,
			"hull": 2200,
			"required_crew": 43,
			"bunks": 112,
			"mass": 230,
			"drag": 5.5,
			"heat_dissipation": 0.65,
			"fuel_capacity": 500,
			"cargo_space": 60,
			"outfit_space": 360,
			"weapon_capacity": 120,
			"engine_capacity": 100
		},
		"description": "The Star Queen is a relic of a more peaceful period of galactic history: a luxury liner for high-end tourists. Every cabin has its own mini-bar, and the bathrooms have marble tile and showers that use actual hot water instead of chemicals or sonic vibrations."
	},
	"Starling": {
		"upper": "Starling",
		"lower": "starling",
		"race": "Remnant",
		"sprite": "ship/starling",
		"attributes": {
			"category": "Light Warship",
			"licenses": {
				"Remnant": 1
			},
			"cost": 8800000,
			"shields": 8800,
			"hull": 4900,
			"required_crew": 6,
			"bunks": 15,
			"mass": 270,
			"drag": 3.8,
			"heat_dissipation": 0.7,
			"fuel_capacity": 900,
			"cargo_space": 36,
			"outfit_space": 312,
			"weapon_capacity": 83,
			"engine_capacity": 94,
			"shield_generation": 1.8,
			"shield_energy": 1.2,
			"hull_repair_rate": 0.8,
			"hull_energy": 0.6,
			"cloak": 0.02,
			"cloaking_energy": 5,
			"cloaking_fuel": 0.1
		},
		"description": [
			"One of the strangest and most useful things that the Remnant discovered in the abandoned worlds of the Ember Waste is alien cloaking technology. They designed their scout ships to be able to cloak when needed, in order to explore alien territory without being seen... or to escape in a hurry after stealing something particularly valuable from those aliens.",
			"The cloaking technology is built into the Starling's hull; it cannot be removed or transferred to another ship."
		]
	},
	"Strong Wind": {
		"upper": "Strong Wind",
		"lower": "strong wind",
		"race": "Wanderer",
		"sprite": "ship/strong wind",
		"attributes": {
			"category": "Medium Warship",
			"licenses": {
				"Wanderer_Military": 1
			},
			"cost": 16100000,
			"shields": 28500,
			"hull": 19600,
			"required_crew": 17,
			"bunks": 39,
			"mass": 260,
			"drag": 4.7,
			"heat_dissipation": 0.7,
			"fuel_capacity": 400,
			"cargo_space": 68,
			"outfit_space": 493,
			"weapon_capacity": 198,
			"engine_capacity": 114
		},
		"description": "The Strong Wind was originally designed for science and exploration, but recently the Wanderers have modified the design to allow it to be used as a warship."
	},
	"Summer Leaf": {
		"upper": "Summer Leaf",
		"lower": "summer leaf",
		"race": "Wanderer",
		"sprite": "ship/summer leaf",
		"attributes": {
			"category": "Light Warship",
			"licenses": {
				"Wanderer": 1
			},
			"cost": 9500000,
			"shields": 14400,
			"hull": 6700,
			"required_crew": 6,
			"bunks": 15,
			"mass": 110,
			"drag": 2.6,
			"heat_dissipation": 0.8,
			"fuel_capacity": 800,
			"cargo_space": 41,
			"outfit_space": 320,
			"weapon_capacity": 84,
			"engine_capacity": 103
		},
		"description": "The Summer Leaf is mostly used by the Wanderers as a light transport, but it is also quite effective in combat."
	},
	"Surveillance Drone": {
		"upper": "Surveillance Drone",
		"lower": "surveillance drone",
		"race": "Human",
		"sprite": "ship/surveillance drone",
		"attributes": {
			"category": "Drone",
			"licenses": {
				"Navy": 1
			},
			"cost": 50000,
			"hull": 300,
			"mass": 15,
			"drag": 0.53,
			"heat_dissipation": 0.9,
			"outfit_space": 53,
			"weapon_capacity": 0,
			"engine_capacity": 28,
			"automaton": 1
		},
		"description": "The Kor Sestor war fleets rely heavily on small, powerful fighters and drones. This ship can carry up to ten of their drones, clamped to the exterior of its hull."
	},
	"Tek Far 78 - Osk": {
		"upper": "Tek Far 78 - Osk",
		"lower": "tek far 78 - osk",
		"race": "Korath",
		"sprite": "ship/tek far 78 osk",
		"attributes": {
			"category": "Medium Warship",
			"cost": 25630000,
			"shields": 27600,
			"hull": 34100,
			"automaton": 1,
			"mass": 690,
			"drag": 10.2,
			"heat_dissipation": 0.55,
			"fuel_capacity": 400,
			"cargo_space": 43,
			"outfit_space": 611,
			"weapon_capacity": 272,
			"engine_capacity": 117,
			"self_destruct": 0.7,
			"ramscoop": 3
		},
		"description": "This carrier is equipped with docking clamps for up to nine fighters. When loaded with a full complement of the powerful Kor Sestor robotic fighters, it is a formidable opponent."
	},
	"Tek Far 109": {
		"upper": "Tek Far 109",
		"lower": "tek far 109",
		"race": "Korath",
		"sprite": "ship/tek far 109",
		"attributes": {
			"category": "Medium Warship",
			"cost": 18290000,
			"shields": 17900,
			"hull": 15800,
			"automaton": 1,
			"mass": 540,
			"drag": 9.1,
			"heat_dissipation": 0.65,
			"fuel_capacity": 400,
			"cargo_space": 31,
			"outfit_space": 491,
			"weapon_capacity": 217,
			"engine_capacity": 98,
			"self_destruct": 0.7,
			"ramscoop": 3
		},
		"description": "The TF109 is designed almost solely for the purpose of carrying a fleet of Kor Sestor fighters and drones. Without them to serve as a protective screen, the ship itself is relatively helpless."
	},
	"Tempest": {
		"upper": "Tempest",
		"lower": "tempest",
		"race": "Wanderer",
		"sprite": "ship/tempest",
		"attributes": {
			"category": "Medium Warship",
			"licenses": {
				"Wanderer_Military": 1
			},
			"cost": 19700000,
			"shields": 42100,
			"hull": 25900,
			"required_crew": 38,
			"bunks": 53,
			"mass": 320,
			"drag": 6.2,
			"heat_dissipation": 0.65,
			"fuel_capacity": 600,
			"cargo_space": 47,
			"outfit_space": 607,
			"weapon_capacity": 271,
			"engine_capacity": 122
		},
		"description": "In response to the Unfettered invasion, the Wanderers have begun digging up ancient warship designs from their archives and putting them back into production. The Tempest is the first purpose-built warship they have manufactured in tens of thousands of years."
	},
	"Vanguard": {
		"upper": "Vanguard",
		"lower": "vanguard",
		"race": "Human",
		"sprite": "ship/vanguard",
		"attributes": {
			"category": "Heavy Warship",
			"cost": 7200000,
			"shields": 9800,
			"hull": 6000,
			"required_crew": 23,
			"bunks": 45,
			"mass": 500,
			"drag": 8,
			"heat_dissipation": 0.6,
			"fuel_capacity": 400,
			"cargo_space": 50,
			"outfit_space": 560,
			"weapon_capacity": 220,
			"engine_capacity": 120
		},
		"description": "The Vanguard is Syndicated Systems' newest warship intended for the heavy anti-pirate defense market. Vanguards offer an unusual feature set, focusing on powerful fixed guns and featuring Syndicated Systems' latest automation technologies, resulting in an atypically low crew complement for a ship its size. Few capital ships will endure for long under the withering fusillade of gunfire that it can unleash against those in front of it."
	},
	"Violin Spider": {
		"upper": "Violin Spider",
		"lower": "violin spider",
		"race": "Hai",
		"sprite": "ship/hai violin spider",
		"attributes": {
			"category": "Fighter",
			"cost": 139000,
			"shields": 1400,
			"hull": 600,
			"required_crew": 1,
			"bunks": 1,
			"mass": 31,
			"drag": 0.9,
			"heat_dissipation": 0.7,
			"outfit_space": 92,
			"weapon_capacity": 19,
			"engine_capacity": 30
		},
		"description": "The Hai fighter is equipped with what most humans would consider the greatest technology available, but all of that high tech comes at a cost."
	},
	"Wasp": {
		"upper": "Wasp",
		"lower": "wasp",
		"race": "Human",
		"sprite": "ship/wasp",
		"attributes": {
			"category": "Interceptor",
			"cost": 400000,
			"shields": 1500,
			"hull": 500,
			"required_crew": 1,
			"bunks": 2,
			"mass": 60,
			"drag": 1.2,
			"heat_dissipation": 0.8,
			"fuel_capacity": 400,
			"cargo_space": 10,
			"outfit_space": 150,
			"weapon_capacity": 28,
			"engine_capacity": 60
		},
		"description": "The wasp is a medium-strength interceptor, designed by Syndicated Shipyards to serve as an escort for cargo vessels. Like most Syndicate ships, it is not particularly pretty, but it at least serves the purpose it was made for."
	},
	"Water Bug": {
		"upper": "Water Bug",
		"lower": "water bug",
		"race": "Hai",
		"sprite": "ship/hai water bug",
		"attributes": {
			"category": "Heavy Freighter",
			"cost": 6500000,
			"shields": 7900,
			"hull": 4500,
			"required_crew": 5,
			"bunks": 29,
			"mass": 270,
			"drag": 5.9,
			"heat_dissipation": 0.75,
			"fuel_capacity": 600,
			"cargo_space": 197,
			"outfit_space": 368,
			"weapon_capacity": 145,
			"engine_capacity": 64
		},
		"description": "The Water Bug is the primary freight ship used by the Hai."
	}
}